// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/envoy/http/path_matcher/config.proto

package path_matcher

import (
	common "cloudesf.googlesource.com/gcpproxy/src/go/proto/api/envoy/http/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/lyft/protoc-gen-validate/validate"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PathMatcherRule struct {
	Pattern               *common.Pattern `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Operation             string          `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	ExtractPathParameters bool            `protobuf:"varint,3,opt,name=extract_path_parameters,json=extractPathParameters,proto3" json:"extract_path_parameters,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}        `json:"-"`
	XXX_unrecognized      []byte          `json:"-"`
	XXX_sizecache         int32           `json:"-"`
}

func (m *PathMatcherRule) Reset()         { *m = PathMatcherRule{} }
func (m *PathMatcherRule) String() string { return proto.CompactTextString(m) }
func (*PathMatcherRule) ProtoMessage()    {}
func (*PathMatcherRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebe96b55b7e4dec, []int{0}
}

func (m *PathMatcherRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathMatcherRule.Unmarshal(m, b)
}
func (m *PathMatcherRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathMatcherRule.Marshal(b, m, deterministic)
}
func (m *PathMatcherRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathMatcherRule.Merge(m, src)
}
func (m *PathMatcherRule) XXX_Size() int {
	return xxx_messageInfo_PathMatcherRule.Size(m)
}
func (m *PathMatcherRule) XXX_DiscardUnknown() {
	xxx_messageInfo_PathMatcherRule.DiscardUnknown(m)
}

var xxx_messageInfo_PathMatcherRule proto.InternalMessageInfo

func (m *PathMatcherRule) GetPattern() *common.Pattern {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (m *PathMatcherRule) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *PathMatcherRule) GetExtractPathParameters() bool {
	if m != nil {
		return m.ExtractPathParameters
	}
	return false
}

type FilterConfig struct {
	Rules                []*PathMatcherRule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *FilterConfig) Reset()         { *m = FilterConfig{} }
func (m *FilterConfig) String() string { return proto.CompactTextString(m) }
func (*FilterConfig) ProtoMessage()    {}
func (*FilterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebe96b55b7e4dec, []int{1}
}

func (m *FilterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterConfig.Unmarshal(m, b)
}
func (m *FilterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterConfig.Marshal(b, m, deterministic)
}
func (m *FilterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterConfig.Merge(m, src)
}
func (m *FilterConfig) XXX_Size() int {
	return xxx_messageInfo_FilterConfig.Size(m)
}
func (m *FilterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FilterConfig proto.InternalMessageInfo

func (m *FilterConfig) GetRules() []*PathMatcherRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func init() {
	proto.RegisterType((*PathMatcherRule)(nil), "google.api.envoy.http.path_matcher.PathMatcherRule")
	proto.RegisterType((*FilterConfig)(nil), "google.api.envoy.http.path_matcher.FilterConfig")
}

func init() {
	proto.RegisterFile("api/envoy/http/path_matcher/config.proto", fileDescriptor_bebe96b55b7e4dec)
}

var fileDescriptor_bebe96b55b7e4dec = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xd9, 0xc6, 0x7f, 0xd9, 0x0a, 0x42, 0x40, 0x1a, 0x7a, 0x0a, 0x11, 0x31, 0xa7, 0x0d,
	0xb4, 0xe0, 0x55, 0x50, 0x10, 0x3c, 0x08, 0x21, 0x37, 0x4f, 0x65, 0x8c, 0x63, 0xb2, 0x90, 0xec,
	0x2e, 0xd3, 0x69, 0xd1, 0xe7, 0xf2, 0xe6, 0xc9, 0xd7, 0xf1, 0x2d, 0x24, 0xd9, 0x56, 0xa5, 0x08,
	0xde, 0x16, 0xbe, 0xfd, 0xfd, 0x66, 0xe6, 0x93, 0x19, 0x38, 0x9d, 0xa3, 0x59, 0xdb, 0xd7, 0xbc,
	0x61, 0x76, 0xb9, 0x03, 0x6e, 0x16, 0x1d, 0x70, 0xd5, 0x20, 0xe5, 0x95, 0x35, 0xcf, 0xba, 0x56,
	0x8e, 0x2c, 0xdb, 0x28, 0xad, 0xad, 0xad, 0x5b, 0x54, 0xe0, 0xb4, 0x1a, 0x00, 0xd5, 0x03, 0xea,
	0x37, 0x30, 0x3d, 0xdb, 0xb1, 0x55, 0xb6, 0xeb, 0xac, 0xe9, 0xa5, 0x8c, 0x64, 0xbc, 0x68, 0x3a,
	0x59, 0x43, 0xab, 0x9f, 0x80, 0x31, 0xdf, 0x3e, 0x7c, 0x90, 0xbe, 0x09, 0x79, 0x52, 0x00, 0x37,
	0xf7, 0xde, 0x56, 0xae, 0x5a, 0x8c, 0xae, 0xe4, 0xe1, 0x86, 0x8e, 0x45, 0x22, 0xb2, 0xf1, 0xec,
	0x5c, 0xfd, 0xbd, 0x87, 0x1f, 0xa5, 0x0a, 0xff, 0xb9, 0xdc, 0x52, 0xd1, 0x85, 0x0c, 0xad, 0x43,
	0x02, 0xd6, 0xd6, 0xc4, 0xa3, 0x44, 0x64, 0xe1, 0x75, 0xf8, 0xfe, 0xf9, 0x11, 0xec, 0xd1, 0x28,
	0x11, 0xe5, 0x4f, 0x16, 0x5d, 0xca, 0x09, 0xbe, 0x30, 0x41, 0xc5, 0x8b, 0xe1, 0x26, 0x07, 0x04,
	0x1d, 0x32, 0xd2, 0x32, 0x0e, 0x12, 0x91, 0x1d, 0x95, 0xa7, 0x9b, 0xb8, 0x5f, 0xb1, 0xf8, 0x0e,
	0xd3, 0x07, 0x79, 0x7c, 0xab, 0x5b, 0x46, 0xba, 0x19, 0xda, 0x8a, 0xee, 0xe4, 0x3e, 0xad, 0x5a,
	0x5c, 0xc6, 0x22, 0x09, 0xb2, 0xf1, 0x6c, 0xae, 0xfe, 0xef, 0x4d, 0xed, 0x5c, 0x5d, 0x7a, 0xc3,
	0xe3, 0xc1, 0xd0, 0xcb, 0xfc, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x0e, 0xf5, 0x5a, 0xa5, 0x01,
	0x00, 0x00,
}
