package(
    default_visibility = [
        "//src/envoy:__subpackages__",
    ],
)

filegroup(
    name = "json_struct_corpus",
    testonly = 1,
    srcs = glob([
        "json_struct/**",
    ]),
)

filegroup(
    name = "iam_token_subscriber_corpus",
    testonly = 1,
    srcs = glob([
        "iam_token_subscriber/**",
    ]),
)
