// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/envoy/http/service_control/config.proto

package google_api_envoy_http_service_control

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	duration "github.com/golang/protobuf/ptypes/duration"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HttpUri struct {
	Uri                  string             `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Cluster              string             `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Timeout              *duration.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *HttpUri) Reset()         { *m = HttpUri{} }
func (m *HttpUri) String() string { return proto.CompactTextString(m) }
func (*HttpUri) ProtoMessage()    {}
func (*HttpUri) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b61cd9ad53a258f, []int{0}
}

func (m *HttpUri) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpUri.Unmarshal(m, b)
}
func (m *HttpUri) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpUri.Marshal(b, m, deterministic)
}
func (m *HttpUri) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpUri.Merge(m, src)
}
func (m *HttpUri) XXX_Size() int {
	return xxx_messageInfo_HttpUri.Size(m)
}
func (m *HttpUri) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpUri.DiscardUnknown(m)
}

var xxx_messageInfo_HttpUri proto.InternalMessageInfo

func (m *HttpUri) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *HttpUri) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *HttpUri) GetTimeout() *duration.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

type ServiceControlCallingConfig struct {
	NetworkFailOpen      *wrappers.BoolValue   `protobuf:"bytes,1,opt,name=network_fail_open,json=networkFailOpen,proto3" json:"network_fail_open,omitempty"`
	CheckTimeoutMs       *wrappers.UInt32Value `protobuf:"bytes,2,opt,name=check_timeout_ms,json=checkTimeoutMs,proto3" json:"check_timeout_ms,omitempty"`
	QuotaTimeoutMs       *wrappers.UInt32Value `protobuf:"bytes,3,opt,name=quota_timeout_ms,json=quotaTimeoutMs,proto3" json:"quota_timeout_ms,omitempty"`
	ReportTimeoutMs      *wrappers.UInt32Value `protobuf:"bytes,4,opt,name=report_timeout_ms,json=reportTimeoutMs,proto3" json:"report_timeout_ms,omitempty"`
	CheckRetries         *wrappers.UInt32Value `protobuf:"bytes,5,opt,name=check_retries,json=checkRetries,proto3" json:"check_retries,omitempty"`
	QuotaRetries         *wrappers.UInt32Value `protobuf:"bytes,6,opt,name=quota_retries,json=quotaRetries,proto3" json:"quota_retries,omitempty"`
	ReportRetries        *wrappers.UInt32Value `protobuf:"bytes,7,opt,name=report_retries,json=reportRetries,proto3" json:"report_retries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ServiceControlCallingConfig) Reset()         { *m = ServiceControlCallingConfig{} }
func (m *ServiceControlCallingConfig) String() string { return proto.CompactTextString(m) }
func (*ServiceControlCallingConfig) ProtoMessage()    {}
func (*ServiceControlCallingConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b61cd9ad53a258f, []int{1}
}

func (m *ServiceControlCallingConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceControlCallingConfig.Unmarshal(m, b)
}
func (m *ServiceControlCallingConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceControlCallingConfig.Marshal(b, m, deterministic)
}
func (m *ServiceControlCallingConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceControlCallingConfig.Merge(m, src)
}
func (m *ServiceControlCallingConfig) XXX_Size() int {
	return xxx_messageInfo_ServiceControlCallingConfig.Size(m)
}
func (m *ServiceControlCallingConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceControlCallingConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceControlCallingConfig proto.InternalMessageInfo

func (m *ServiceControlCallingConfig) GetNetworkFailOpen() *wrappers.BoolValue {
	if m != nil {
		return m.NetworkFailOpen
	}
	return nil
}

func (m *ServiceControlCallingConfig) GetCheckTimeoutMs() *wrappers.UInt32Value {
	if m != nil {
		return m.CheckTimeoutMs
	}
	return nil
}

func (m *ServiceControlCallingConfig) GetQuotaTimeoutMs() *wrappers.UInt32Value {
	if m != nil {
		return m.QuotaTimeoutMs
	}
	return nil
}

func (m *ServiceControlCallingConfig) GetReportTimeoutMs() *wrappers.UInt32Value {
	if m != nil {
		return m.ReportTimeoutMs
	}
	return nil
}

func (m *ServiceControlCallingConfig) GetCheckRetries() *wrappers.UInt32Value {
	if m != nil {
		return m.CheckRetries
	}
	return nil
}

func (m *ServiceControlCallingConfig) GetQuotaRetries() *wrappers.UInt32Value {
	if m != nil {
		return m.QuotaRetries
	}
	return nil
}

func (m *ServiceControlCallingConfig) GetReportRetries() *wrappers.UInt32Value {
	if m != nil {
		return m.ReportRetries
	}
	return nil
}

type Service struct {
	ServiceName               string   `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceConfigId           string   `protobuf:"bytes,2,opt,name=service_config_id,json=serviceConfigId,proto3" json:"service_config_id,omitempty"`
	ProducerProjectId         string   `protobuf:"bytes,3,opt,name=producer_project_id,json=producerProjectId,proto3" json:"producer_project_id,omitempty"`
	ServiceControlUri         *HttpUri `protobuf:"bytes,5,opt,name=service_control_uri,json=serviceControlUri,proto3" json:"service_control_uri,omitempty"`
	TokenCluster              string   `protobuf:"bytes,6,opt,name=token_cluster,json=tokenCluster,proto3" json:"token_cluster,omitempty"`
	ServiceConfig             *any.Any `protobuf:"bytes,7,opt,name=service_config,json=serviceConfig,proto3" json:"service_config,omitempty"`
	BackendProtocol           string   `protobuf:"bytes,8,opt,name=backend_protocol,json=backendProtocol,proto3" json:"backend_protocol,omitempty"`
	LogRequestHeaders         []string `protobuf:"bytes,9,rep,name=log_request_headers,json=logRequestHeaders,proto3" json:"log_request_headers,omitempty"`
	LogResponseHeaders        []string `protobuf:"bytes,10,rep,name=log_response_headers,json=logResponseHeaders,proto3" json:"log_response_headers,omitempty"`
	MinStreamReportIntervalMs uint64   `protobuf:"varint,11,opt,name=min_stream_report_interval_ms,json=minStreamReportIntervalMs,proto3" json:"min_stream_report_interval_ms,omitempty"`
	LogJwtPayloads            []string `protobuf:"bytes,12,rep,name=log_jwt_payloads,json=logJwtPayloads,proto3" json:"log_jwt_payloads,omitempty"`
	JwtPayloadMetadataName    string   `protobuf:"bytes,13,opt,name=jwt_payload_metadata_name,json=jwtPayloadMetadataName,proto3" json:"jwt_payload_metadata_name,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b61cd9ad53a258f, []int{2}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Service) GetServiceConfigId() string {
	if m != nil {
		return m.ServiceConfigId
	}
	return ""
}

func (m *Service) GetProducerProjectId() string {
	if m != nil {
		return m.ProducerProjectId
	}
	return ""
}

func (m *Service) GetServiceControlUri() *HttpUri {
	if m != nil {
		return m.ServiceControlUri
	}
	return nil
}

func (m *Service) GetTokenCluster() string {
	if m != nil {
		return m.TokenCluster
	}
	return ""
}

func (m *Service) GetServiceConfig() *any.Any {
	if m != nil {
		return m.ServiceConfig
	}
	return nil
}

func (m *Service) GetBackendProtocol() string {
	if m != nil {
		return m.BackendProtocol
	}
	return ""
}

func (m *Service) GetLogRequestHeaders() []string {
	if m != nil {
		return m.LogRequestHeaders
	}
	return nil
}

func (m *Service) GetLogResponseHeaders() []string {
	if m != nil {
		return m.LogResponseHeaders
	}
	return nil
}

func (m *Service) GetMinStreamReportIntervalMs() uint64 {
	if m != nil {
		return m.MinStreamReportIntervalMs
	}
	return 0
}

func (m *Service) GetLogJwtPayloads() []string {
	if m != nil {
		return m.LogJwtPayloads
	}
	return nil
}

func (m *Service) GetJwtPayloadMetadataName() string {
	if m != nil {
		return m.JwtPayloadMetadataName
	}
	return ""
}

type GcpAttributes struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Zone                 string   `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	Platform             string   `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GcpAttributes) Reset()         { *m = GcpAttributes{} }
func (m *GcpAttributes) String() string { return proto.CompactTextString(m) }
func (*GcpAttributes) ProtoMessage()    {}
func (*GcpAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b61cd9ad53a258f, []int{3}
}

func (m *GcpAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GcpAttributes.Unmarshal(m, b)
}
func (m *GcpAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GcpAttributes.Marshal(b, m, deterministic)
}
func (m *GcpAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GcpAttributes.Merge(m, src)
}
func (m *GcpAttributes) XXX_Size() int {
	return xxx_messageInfo_GcpAttributes.Size(m)
}
func (m *GcpAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_GcpAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_GcpAttributes proto.InternalMessageInfo

func (m *GcpAttributes) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *GcpAttributes) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *GcpAttributes) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

type FilterConfig struct {
	Services             []*Service                   `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Requirements         []*Requirement               `protobuf:"bytes,2,rep,name=requirements,proto3" json:"requirements,omitempty"`
	GcpAttributes        *GcpAttributes               `protobuf:"bytes,3,opt,name=gcp_attributes,json=gcpAttributes,proto3" json:"gcp_attributes,omitempty"`
	TokenUrl             string                       `protobuf:"bytes,4,opt,name=token_url,json=tokenUrl,proto3" json:"token_url,omitempty"`
	ScCallingConfig      *ServiceControlCallingConfig `protobuf:"bytes,5,opt,name=sc_calling_config,json=scCallingConfig,proto3" json:"sc_calling_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *FilterConfig) Reset()         { *m = FilterConfig{} }
func (m *FilterConfig) String() string { return proto.CompactTextString(m) }
func (*FilterConfig) ProtoMessage()    {}
func (*FilterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b61cd9ad53a258f, []int{4}
}

func (m *FilterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterConfig.Unmarshal(m, b)
}
func (m *FilterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterConfig.Marshal(b, m, deterministic)
}
func (m *FilterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterConfig.Merge(m, src)
}
func (m *FilterConfig) XXX_Size() int {
	return xxx_messageInfo_FilterConfig.Size(m)
}
func (m *FilterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FilterConfig proto.InternalMessageInfo

func (m *FilterConfig) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *FilterConfig) GetRequirements() []*Requirement {
	if m != nil {
		return m.Requirements
	}
	return nil
}

func (m *FilterConfig) GetGcpAttributes() *GcpAttributes {
	if m != nil {
		return m.GcpAttributes
	}
	return nil
}

func (m *FilterConfig) GetTokenUrl() string {
	if m != nil {
		return m.TokenUrl
	}
	return ""
}

func (m *FilterConfig) GetScCallingConfig() *ServiceControlCallingConfig {
	if m != nil {
		return m.ScCallingConfig
	}
	return nil
}

func init() {
	proto.RegisterType((*HttpUri)(nil), "google.api.envoy.http.service_control.HttpUri")
	proto.RegisterType((*ServiceControlCallingConfig)(nil), "google.api.envoy.http.service_control.ServiceControlCallingConfig")
	proto.RegisterType((*Service)(nil), "google.api.envoy.http.service_control.Service")
	proto.RegisterType((*GcpAttributes)(nil), "google.api.envoy.http.service_control.GcpAttributes")
	proto.RegisterType((*FilterConfig)(nil), "google.api.envoy.http.service_control.FilterConfig")
}

func init() {
	proto.RegisterFile("api/envoy/http/service_control/config.proto", fileDescriptor_3b61cd9ad53a258f)
}

var fileDescriptor_3b61cd9ad53a258f = []byte{
	// 894 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x6e, 0x23, 0x35,
	0x18, 0x55, 0x9a, 0xfe, 0x24, 0x5f, 0xfe, 0x1a, 0x77, 0x05, 0x69, 0xcb, 0xa2, 0x28, 0x08, 0x29,
	0x08, 0x34, 0x59, 0x65, 0xe1, 0x62, 0xc5, 0x05, 0xb4, 0x41, 0xa5, 0x5d, 0xa9, 0x50, 0x79, 0xe9,
	0xde, 0x20, 0xed, 0xc8, 0x9d, 0x71, 0xa6, 0x6e, 0x3d, 0xf6, 0xac, 0xed, 0x69, 0x55, 0x1e, 0x01,
	0xf1, 0x08, 0x3c, 0xc1, 0x3e, 0x02, 0x57, 0xbc, 0x0e, 0x6f, 0x81, 0xc6, 0xf6, 0xa4, 0xf9, 0x01,
	0x6d, 0xf6, 0x6e, 0xc6, 0xe7, 0x3b, 0xc7, 0xf6, 0xe7, 0x73, 0x6c, 0xf8, 0x92, 0x64, 0x6c, 0x44,
	0xc5, 0x9d, 0x7c, 0x18, 0x5d, 0x1b, 0x93, 0x8d, 0x34, 0x55, 0x77, 0x2c, 0xa2, 0x61, 0x24, 0x85,
	0x51, 0x92, 0x8f, 0x22, 0x29, 0xa6, 0x2c, 0x09, 0x32, 0x25, 0x8d, 0x44, 0x9f, 0x27, 0x52, 0x26,
	0x9c, 0x06, 0x24, 0x63, 0x81, 0xe5, 0x04, 0x05, 0x27, 0x58, 0xe2, 0x1c, 0x3c, 0x7b, 0x8f, 0xa6,
	0xa2, 0x6f, 0x73, 0xa6, 0x68, 0x4a, 0x85, 0x71, 0xc2, 0x07, 0xfb, 0x4e, 0x78, 0x64, 0xff, 0xae,
	0xf2, 0xe9, 0x88, 0x88, 0x07, 0x0f, 0x7d, 0xba, 0x0c, 0xdd, 0x2b, 0x92, 0x65, 0x54, 0xe9, 0xff,
	0xc3, 0xe3, 0x5c, 0x11, 0xc3, 0xa4, 0xf0, 0xf8, 0xc7, 0x77, 0x84, 0xb3, 0x98, 0x18, 0x3a, 0x2a,
	0x3f, 0x1c, 0x30, 0xf8, 0xa3, 0x02, 0x3b, 0xa7, 0xc6, 0x64, 0x97, 0x8a, 0xa1, 0x43, 0xa8, 0xe6,
	0x8a, 0xf5, 0x2a, 0xfd, 0xca, 0xb0, 0x7e, 0x5c, 0xff, 0xeb, 0x9f, 0xbf, 0xab, 0x9b, 0x6a, 0xa3,
	0x5f, 0xc1, 0xc5, 0x28, 0xfa, 0x0c, 0x76, 0x22, 0x9e, 0x6b, 0x43, 0x55, 0x6f, 0x63, 0xb9, 0xa0,
	0x44, 0xd0, 0x77, 0xb0, 0x63, 0x58, 0x4a, 0x65, 0x6e, 0x7a, 0xd5, 0x7e, 0x65, 0xd8, 0x18, 0xef,
	0x07, 0xbe, 0x59, 0xe5, 0xc2, 0x82, 0x1f, 0xfc, 0xc2, 0x8e, 0xa1, 0xe0, 0x6f, 0xbd, 0xab, 0x6c,
	0xd4, 0x2a, 0xb8, 0x64, 0x0d, 0x7e, 0xdf, 0x84, 0xc3, 0x57, 0xae, 0x51, 0x13, 0xd7, 0xa7, 0x09,
	0xe1, 0x9c, 0x89, 0x64, 0x62, 0x4f, 0x00, 0x9d, 0x40, 0x57, 0x50, 0x73, 0x2f, 0xd5, 0x6d, 0x38,
	0x25, 0x8c, 0x87, 0x32, 0xa3, 0xc2, 0x2e, 0xb8, 0x31, 0x3e, 0x58, 0x99, 0xea, 0x58, 0x4a, 0xfe,
	0x9a, 0xf0, 0x9c, 0xe2, 0x8e, 0x27, 0x9d, 0x10, 0xc6, 0x7f, 0xce, 0xa8, 0x40, 0x27, 0xb0, 0x1b,
	0x5d, 0xd3, 0xe8, 0x36, 0xf4, 0x13, 0x87, 0xa9, 0xb6, 0xdb, 0x6a, 0x8c, 0x3f, 0x59, 0x91, 0xb9,
	0x3c, 0x13, 0xe6, 0xf9, 0xd8, 0x09, 0xb5, 0x2d, 0xeb, 0x17, 0x47, 0x3a, 0xd7, 0x85, 0xce, 0xdb,
	0x5c, 0x1a, 0x32, 0xaf, 0x53, 0x5d, 0x47, 0xc7, 0xb2, 0x1e, 0x75, 0x4e, 0xa1, 0xab, 0x68, 0x26,
	0x95, 0x99, 0x17, 0xda, 0x5c, 0x43, 0xa8, 0xe3, 0x68, 0x8f, 0x4a, 0x47, 0xd0, 0x72, 0x3b, 0x53,
	0xd4, 0x28, 0x46, 0x75, 0x6f, 0x6b, 0x0d, 0x95, 0xa6, 0xa5, 0x60, 0xc7, 0x28, 0x24, 0xdc, 0xa6,
	0x4a, 0x89, 0xed, 0x75, 0x24, 0x2c, 0xa5, 0x94, 0x98, 0x40, 0xdb, 0xef, 0xa7, 0xd4, 0xd8, 0x59,
	0x43, 0xa3, 0xe5, 0x38, 0x5e, 0x64, 0xf0, 0x6e, 0x0b, 0x76, 0xbc, 0x19, 0xd0, 0x57, 0xd0, 0x2c,
	0x03, 0x24, 0x48, 0x4a, 0x57, 0x4d, 0xda, 0xf0, 0xf0, 0x4f, 0x24, 0xa5, 0xe8, 0x1b, 0xe8, 0xce,
	0xc5, 0x6d, 0xca, 0x92, 0x90, 0xc5, 0xab, 0xb6, 0xed, 0xe8, 0x99, 0xd3, 0xa6, 0x2c, 0x39, 0x8b,
	0xd1, 0x0b, 0xd8, 0xcb, 0x94, 0x8c, 0xf3, 0x88, 0xaa, 0x30, 0x53, 0xf2, 0x86, 0x46, 0xa6, 0x20,
	0x56, 0x97, 0x89, 0xdd, 0xb2, 0xea, 0xc2, 0x15, 0x9d, 0xc5, 0xe8, 0x0d, 0xec, 0x2d, 0x05, 0x3c,
	0x2c, 0xb2, 0xe4, 0x9a, 0x1f, 0x04, 0x6b, 0x5d, 0x19, 0x81, 0x0f, 0x22, 0xee, 0xea, 0x85, 0x08,
	0x14, 0xd9, 0x0c, 0xa0, 0x65, 0xe4, 0x2d, 0x15, 0x61, 0x19, 0xc2, 0xed, 0xe5, 0x45, 0x35, 0x2d,
	0x3e, 0xf1, 0x49, 0xfc, 0x16, 0xda, 0x8b, 0x1d, 0xf0, 0x07, 0xf0, 0x64, 0xe5, 0x00, 0x8e, 0xc4,
	0x03, 0x6e, 0x2d, 0x74, 0x02, 0x7d, 0x01, 0xbb, 0x57, 0x24, 0xba, 0xa5, 0x22, 0x0e, 0x6d, 0x59,
	0x24, 0x79, 0xaf, 0x56, 0xcc, 0x87, 0x3b, 0x7e, 0xfc, 0xc2, 0x0f, 0xa3, 0x00, 0xf6, 0xb8, 0x4c,
	0xc2, 0xe2, 0x32, 0xa3, 0xda, 0x84, 0xd7, 0x94, 0xc4, 0x54, 0xe9, 0x5e, 0xbd, 0x5f, 0x1d, 0xd6,
	0x71, 0x97, 0xcb, 0x04, 0x3b, 0xe4, 0xd4, 0x01, 0xe8, 0x19, 0x3c, 0x71, 0xf5, 0x3a, 0x93, 0x42,
	0xd3, 0x19, 0x01, 0x2c, 0x01, 0x59, 0x82, 0x83, 0x4a, 0xc6, 0xf7, 0xf0, 0x34, 0x65, 0x22, 0xd4,
	0x46, 0x51, 0x92, 0x86, 0xde, 0x55, 0x4c, 0x18, 0xaa, 0xee, 0x08, 0x2f, 0x62, 0xd2, 0xe8, 0x57,
	0x86, 0x9b, 0x78, 0x3f, 0x65, 0xe2, 0x95, 0xad, 0xc1, 0xb6, 0xe4, 0xcc, 0x57, 0x9c, 0x6b, 0x34,
	0x84, 0xdd, 0x62, 0xce, 0x9b, 0x7b, 0x13, 0x66, 0xe4, 0x81, 0x4b, 0x12, 0xeb, 0x5e, 0xd3, 0xce,
	0xd7, 0xe6, 0x32, 0x79, 0x79, 0x6f, 0x2e, 0xfc, 0x28, 0x7a, 0x01, 0xfb, 0x73, 0x55, 0x61, 0x4a,
	0x0d, 0x89, 0x89, 0x21, 0xce, 0x72, 0x2d, 0xdb, 0x81, 0x8f, 0x6e, 0x66, 0xf5, 0xe7, 0x1e, 0x2e,
	0x2c, 0x37, 0x78, 0x03, 0xad, 0x1f, 0xa3, 0xec, 0xc8, 0x18, 0xc5, 0xae, 0x72, 0x43, 0x35, 0x7a,
	0x0a, 0x30, 0xe7, 0x21, 0xeb, 0x57, 0x5c, 0xcf, 0x66, 0x86, 0x41, 0xb0, 0xf9, 0x9b, 0x14, 0xd4,
	0xb9, 0x12, 0xdb, 0x6f, 0x74, 0x00, 0xb5, 0x8c, 0x13, 0x33, 0x95, 0x2a, 0x75, 0xa6, 0xc3, 0xb3,
	0xff, 0xc1, 0x9f, 0x55, 0x68, 0x9e, 0x30, 0x6e, 0xa8, 0xf2, 0x87, 0xf4, 0x12, 0x6a, 0xfe, 0xd4,
	0x74, 0xaf, 0xd2, 0xaf, 0x7e, 0x80, 0xcd, 0x7c, 0xa6, 0xf0, 0x8c, 0x8f, 0x5e, 0x43, 0x73, 0xee,
	0x39, 0x2a, 0xae, 0xc2, 0x42, 0x6f, 0xbc, 0xa6, 0x1e, 0x7e, 0xa4, 0xe2, 0x05, 0x1d, 0xf4, 0x2b,
	0xb4, 0x93, 0x28, 0x0b, 0xc9, 0xac, 0x2b, 0xfe, 0x72, 0xfc, 0x7a, 0x4d, 0xe5, 0x85, 0x8e, 0xe2,
	0x56, 0xb2, 0xd0, 0xe0, 0x43, 0xa8, 0xbb, 0x48, 0xe4, 0x8a, 0xdb, 0xbb, 0xb2, 0x8e, 0x6b, 0x76,
	0xe0, 0x52, 0x71, 0x24, 0xa0, 0xab, 0xa3, 0x30, 0x72, 0x8f, 0x47, 0x19, 0x01, 0x97, 0xc6, 0xe3,
	0x0f, 0x6b, 0xd3, 0x7f, 0xbd, 0x43, 0xb8, 0xa3, 0xa3, 0x85, 0x81, 0xab, 0x6d, 0x1b, 0x94, 0xe7,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x35, 0xd9, 0x4d, 0xe4, 0x4a, 0x08, 0x00, 0x00,
}
