// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/envoy/http/service_control/config.proto

package service_control

import (
	common "cloudesf.googlesource.com/gcpproxy/src/go/proto/api/envoy/http/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	_ "github.com/lyft/protoc-gen-validate/validate"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HttpUri struct {
	Uri                  string             `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Cluster              string             `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Timeout              *duration.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *HttpUri) Reset()         { *m = HttpUri{} }
func (m *HttpUri) String() string { return proto.CompactTextString(m) }
func (*HttpUri) ProtoMessage()    {}
func (*HttpUri) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b61cd9ad53a258f, []int{0}
}

func (m *HttpUri) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpUri.Unmarshal(m, b)
}
func (m *HttpUri) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpUri.Marshal(b, m, deterministic)
}
func (m *HttpUri) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpUri.Merge(m, src)
}
func (m *HttpUri) XXX_Size() int {
	return xxx_messageInfo_HttpUri.Size(m)
}
func (m *HttpUri) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpUri.DiscardUnknown(m)
}

var xxx_messageInfo_HttpUri proto.InternalMessageInfo

func (m *HttpUri) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *HttpUri) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *HttpUri) GetTimeout() *duration.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

type ServiceControlRule struct {
	Pattern              *common.Pattern `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Requires             *Requirement    `protobuf:"bytes,2,opt,name=requires,proto3" json:"requires,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ServiceControlRule) Reset()         { *m = ServiceControlRule{} }
func (m *ServiceControlRule) String() string { return proto.CompactTextString(m) }
func (*ServiceControlRule) ProtoMessage()    {}
func (*ServiceControlRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b61cd9ad53a258f, []int{1}
}

func (m *ServiceControlRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceControlRule.Unmarshal(m, b)
}
func (m *ServiceControlRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceControlRule.Marshal(b, m, deterministic)
}
func (m *ServiceControlRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceControlRule.Merge(m, src)
}
func (m *ServiceControlRule) XXX_Size() int {
	return xxx_messageInfo_ServiceControlRule.Size(m)
}
func (m *ServiceControlRule) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceControlRule.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceControlRule proto.InternalMessageInfo

func (m *ServiceControlRule) GetPattern() *common.Pattern {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (m *ServiceControlRule) GetRequires() *Requirement {
	if m != nil {
		return m.Requires
	}
	return nil
}

type Service struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceConfigId      string   `protobuf:"bytes,2,opt,name=service_config_id,json=serviceConfigId,proto3" json:"service_config_id,omitempty"`
	ProducerProjectId    string   `protobuf:"bytes,3,opt,name=producer_project_id,json=producerProjectId,proto3" json:"producer_project_id,omitempty"`
	ServiceControlUri    *HttpUri `protobuf:"bytes,5,opt,name=service_control_uri,json=serviceControlUri,proto3" json:"service_control_uri,omitempty"`
	TokenCluster         string   `protobuf:"bytes,6,opt,name=token_cluster,json=tokenCluster,proto3" json:"token_cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b61cd9ad53a258f, []int{2}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Service) GetServiceConfigId() string {
	if m != nil {
		return m.ServiceConfigId
	}
	return ""
}

func (m *Service) GetProducerProjectId() string {
	if m != nil {
		return m.ProducerProjectId
	}
	return ""
}

func (m *Service) GetServiceControlUri() *HttpUri {
	if m != nil {
		return m.ServiceControlUri
	}
	return nil
}

func (m *Service) GetTokenCluster() string {
	if m != nil {
		return m.TokenCluster
	}
	return ""
}

type FilterConfig struct {
	Services             []*Service            `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Rules                []*ServiceControlRule `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FilterConfig) Reset()         { *m = FilterConfig{} }
func (m *FilterConfig) String() string { return proto.CompactTextString(m) }
func (*FilterConfig) ProtoMessage()    {}
func (*FilterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b61cd9ad53a258f, []int{3}
}

func (m *FilterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterConfig.Unmarshal(m, b)
}
func (m *FilterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterConfig.Marshal(b, m, deterministic)
}
func (m *FilterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterConfig.Merge(m, src)
}
func (m *FilterConfig) XXX_Size() int {
	return xxx_messageInfo_FilterConfig.Size(m)
}
func (m *FilterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FilterConfig proto.InternalMessageInfo

func (m *FilterConfig) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *FilterConfig) GetRules() []*ServiceControlRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func init() {
	proto.RegisterType((*HttpUri)(nil), "google.api.envoy.http.service_control.HttpUri")
	proto.RegisterType((*ServiceControlRule)(nil), "google.api.envoy.http.service_control.ServiceControlRule")
	proto.RegisterType((*Service)(nil), "google.api.envoy.http.service_control.Service")
	proto.RegisterType((*FilterConfig)(nil), "google.api.envoy.http.service_control.FilterConfig")
}

func init() {
	proto.RegisterFile("api/envoy/http/service_control/config.proto", fileDescriptor_3b61cd9ad53a258f)
}

var fileDescriptor_3b61cd9ad53a258f = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0xc7, 0xd9, 0xc4, 0x6b, 0xae, 0x73, 0x27, 0x7a, 0xdb, 0x07, 0xcf, 0x0a, 0x72, 0x5c, 0x29,
	0x14, 0x94, 0x8d, 0x9c, 0xf8, 0xd0, 0x27, 0xa1, 0x15, 0xb1, 0x0a, 0x5a, 0x22, 0xbe, 0xf8, 0x60,
	0x48, 0x93, 0xb9, 0xb8, 0x9a, 0x64, 0xe3, 0x66, 0xf7, 0xc0, 0xaf, 0x20, 0x7e, 0x12, 0xfd, 0x04,
	0x0a, 0x82, 0x5f, 0xc7, 0x6f, 0x21, 0xc9, 0xee, 0x9e, 0x6d, 0x2a, 0xb4, 0x7d, 0x4b, 0x76, 0xe6,
	0xff, 0x9f, 0x99, 0xdf, 0x0c, 0xdc, 0x4b, 0x6a, 0x1e, 0x62, 0xb5, 0x12, 0x9f, 0xc3, 0xf7, 0x4a,
	0xd5, 0x61, 0x83, 0x72, 0xc5, 0x53, 0x8c, 0x53, 0x51, 0x29, 0x29, 0x8a, 0x30, 0x15, 0xd5, 0x92,
	0xe7, 0xac, 0x96, 0x42, 0x09, 0xba, 0x9b, 0x0b, 0x91, 0x17, 0xc8, 0x92, 0x9a, 0xb3, 0x4e, 0xc3,
	0x5a, 0x0d, 0xeb, 0x69, 0xb6, 0x77, 0x7a, 0x9e, 0xa9, 0x28, 0x4b, 0x51, 0x85, 0x75, 0xa2, 0x14,
	0xca, 0xca, 0x78, 0x6d, 0x3f, 0xb8, 0xa0, 0xb0, 0xc4, 0x4f, 0x9a, 0x4b, 0x2c, 0xb1, 0x52, 0x56,
	0x71, 0xd7, 0x54, 0x0f, 0xbb, 0xbf, 0x13, 0xbd, 0x0c, 0x33, 0x2d, 0x13, 0xc5, 0x85, 0x73, 0xbc,
	0xb5, 0x4a, 0x0a, 0x9e, 0x25, 0x0a, 0x43, 0xf7, 0x61, 0x02, 0xf3, 0xaf, 0x04, 0x82, 0x67, 0x4a,
	0xd5, 0x6f, 0x24, 0xa7, 0x77, 0xc0, 0xd7, 0x92, 0x4f, 0xc9, 0x8c, 0xec, 0x6d, 0x1e, 0x6c, 0xfe,
	0xfc, 0xf3, 0xdb, 0xbf, 0x26, 0xbd, 0x19, 0x89, 0xda, 0x57, 0xba, 0x03, 0x41, 0x5a, 0xe8, 0x46,
	0xa1, 0x9c, 0x7a, 0xfd, 0x04, 0x17, 0xa1, 0x8f, 0x21, 0x50, 0xbc, 0x44, 0xa1, 0xd5, 0xd4, 0x9f,
	0x91, 0xbd, 0xd1, 0xe2, 0x36, 0xb3, 0x58, 0x5c, 0x63, 0xec, 0x89, 0x6d, 0xec, 0x00, 0x5a, 0xfd,
	0xe0, 0x1b, 0xf1, 0x86, 0x24, 0x72, 0xaa, 0xf9, 0x2f, 0x02, 0xf4, 0xb5, 0x99, 0xf6, 0xd0, 0x0c,
	0x1b, 0xe9, 0x02, 0xe9, 0x0b, 0x08, 0x2c, 0xa1, 0xae, 0xbb, 0xd1, 0x62, 0x97, 0xfd, 0x1f, 0xb7,
	0xc1, 0xc9, 0x8e, 0x4d, 0xb2, 0xad, 0xf1, 0x85, 0x78, 0x37, 0x49, 0xe4, 0x1c, 0xe8, 0x5b, 0x18,
	0x5a, 0x80, 0x4d, 0x37, 0xca, 0x68, 0xb1, 0x60, 0x97, 0x5a, 0x1e, 0x8b, 0xfe, 0x71, 0x3f, 0x63,
	0xbd, 0xf6, 0x9b, 0xff, 0xf0, 0x20, 0xb0, 0xfd, 0xd3, 0xfb, 0x30, 0x76, 0x06, 0x55, 0x52, 0xe2,
	0x79, 0xae, 0x23, 0x1b, 0x7e, 0x99, 0x94, 0x48, 0x1f, 0xc1, 0xe4, 0x54, 0xb9, 0x25, 0xcf, 0x63,
	0x9e, 0x9d, 0x27, 0x7d, 0xa3, 0x59, 0xc3, 0x59, 0xf2, 0xfc, 0x28, 0xa3, 0xfb, 0xb0, 0x55, 0x4b,
	0x91, 0xe9, 0x14, 0x65, 0x5c, 0x4b, 0xf1, 0x01, 0x53, 0xd5, 0x0a, 0xfd, 0xbe, 0x70, 0xe2, 0xb2,
	0x8e, 0x4d, 0xd2, 0x51, 0x46, 0xdf, 0xc1, 0x56, 0x6f, 0xc0, 0xb8, 0x5d, 0xff, 0xa0, 0x43, 0xc2,
	0x2e, 0x89, 0xc4, 0xde, 0x4e, 0x34, 0x69, 0xce, 0x6c, 0xad, 0x3d, 0x27, 0x06, 0xd7, 0x95, 0xf8,
	0x88, 0x55, 0xec, 0xee, 0x66, 0xa3, 0xdf, 0xd4, 0xb8, 0x8b, 0x1f, 0x9a, 0xf0, 0xfc, 0x3b, 0x81,
	0xf1, 0x53, 0x5e, 0x28, 0x94, 0x66, 0x3a, 0xfa, 0x1c, 0x86, 0xd6, 0xb5, 0x99, 0x92, 0x99, 0x7f,
	0x85, 0xae, 0xec, 0x0a, 0xa2, 0xb5, 0x9e, 0xbe, 0x82, 0x81, 0xd4, 0x45, 0xb7, 0xf1, 0xd6, 0x68,
	0xff, 0x6a, 0x46, 0xa7, 0x6e, 0x31, 0x32, 0x3e, 0x27, 0x1b, 0xdd, 0x45, 0x3f, 0xfc, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x42, 0x12, 0x92, 0x15, 0x25, 0x04, 0x00, 0x00,
}
