// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/envoy/http/service_control/requirement.proto

package service_control

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/lyft/protoc-gen-validate/validate"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type APIKey struct {
	// Types that are valid to be assigned to Key:
	//	*APIKey_Query
	//	*APIKey_Header
	//	*APIKey_Cookie
	Key                  isAPIKey_Key `protobuf_oneof:"key"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *APIKey) Reset()         { *m = APIKey{} }
func (m *APIKey) String() string { return proto.CompactTextString(m) }
func (*APIKey) ProtoMessage()    {}
func (*APIKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_3dda622705118f3d, []int{0}
}

func (m *APIKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIKey.Unmarshal(m, b)
}
func (m *APIKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIKey.Marshal(b, m, deterministic)
}
func (m *APIKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIKey.Merge(m, src)
}
func (m *APIKey) XXX_Size() int {
	return xxx_messageInfo_APIKey.Size(m)
}
func (m *APIKey) XXX_DiscardUnknown() {
	xxx_messageInfo_APIKey.DiscardUnknown(m)
}

var xxx_messageInfo_APIKey proto.InternalMessageInfo

type isAPIKey_Key interface {
	isAPIKey_Key()
}

type APIKey_Query struct {
	Query string `protobuf:"bytes,1,opt,name=query,proto3,oneof"`
}

type APIKey_Header struct {
	Header string `protobuf:"bytes,2,opt,name=header,proto3,oneof"`
}

type APIKey_Cookie struct {
	Cookie string `protobuf:"bytes,3,opt,name=cookie,proto3,oneof"`
}

func (*APIKey_Query) isAPIKey_Key() {}

func (*APIKey_Header) isAPIKey_Key() {}

func (*APIKey_Cookie) isAPIKey_Key() {}

func (m *APIKey) GetKey() isAPIKey_Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *APIKey) GetQuery() string {
	if x, ok := m.GetKey().(*APIKey_Query); ok {
		return x.Query
	}
	return ""
}

func (m *APIKey) GetHeader() string {
	if x, ok := m.GetKey().(*APIKey_Header); ok {
		return x.Header
	}
	return ""
}

func (m *APIKey) GetCookie() string {
	if x, ok := m.GetKey().(*APIKey_Cookie); ok {
		return x.Cookie
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*APIKey) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _APIKey_OneofMarshaler, _APIKey_OneofUnmarshaler, _APIKey_OneofSizer, []interface{}{
		(*APIKey_Query)(nil),
		(*APIKey_Header)(nil),
		(*APIKey_Cookie)(nil),
	}
}

func _APIKey_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*APIKey)
	// key
	switch x := m.Key.(type) {
	case *APIKey_Query:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Query)
	case *APIKey_Header:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Header)
	case *APIKey_Cookie:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Cookie)
	case nil:
	default:
		return fmt.Errorf("APIKey.Key has unexpected type %T", x)
	}
	return nil
}

func _APIKey_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*APIKey)
	switch tag {
	case 1: // key.query
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Key = &APIKey_Query{x}
		return true, err
	case 2: // key.header
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Key = &APIKey_Header{x}
		return true, err
	case 3: // key.cookie
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Key = &APIKey_Cookie{x}
		return true, err
	default:
		return false, nil
	}
}

func _APIKey_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*APIKey)
	// key
	switch x := m.Key.(type) {
	case *APIKey_Query:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Query)))
		n += len(x.Query)
	case *APIKey_Header:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Header)))
		n += len(x.Header)
	case *APIKey_Cookie:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Cookie)))
		n += len(x.Cookie)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type APIKeyRequirement struct {
	ApiKeys              []*APIKey `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	AllowWithoutApiKey   bool      `protobuf:"varint,2,opt,name=allow_without_api_key,json=allowWithoutApiKey,proto3" json:"allow_without_api_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *APIKeyRequirement) Reset()         { *m = APIKeyRequirement{} }
func (m *APIKeyRequirement) String() string { return proto.CompactTextString(m) }
func (*APIKeyRequirement) ProtoMessage()    {}
func (*APIKeyRequirement) Descriptor() ([]byte, []int) {
	return fileDescriptor_3dda622705118f3d, []int{1}
}

func (m *APIKeyRequirement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIKeyRequirement.Unmarshal(m, b)
}
func (m *APIKeyRequirement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIKeyRequirement.Marshal(b, m, deterministic)
}
func (m *APIKeyRequirement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIKeyRequirement.Merge(m, src)
}
func (m *APIKeyRequirement) XXX_Size() int {
	return xxx_messageInfo_APIKeyRequirement.Size(m)
}
func (m *APIKeyRequirement) XXX_DiscardUnknown() {
	xxx_messageInfo_APIKeyRequirement.DiscardUnknown(m)
}

var xxx_messageInfo_APIKeyRequirement proto.InternalMessageInfo

func (m *APIKeyRequirement) GetApiKeys() []*APIKey {
	if m != nil {
		return m.ApiKeys
	}
	return nil
}

func (m *APIKeyRequirement) GetAllowWithoutApiKey() bool {
	if m != nil {
		return m.AllowWithoutApiKey
	}
	return false
}

type Requirement struct {
	ServiceName          string             `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	OperationName        string             `protobuf:"bytes,2,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	ApiKey               *APIKeyRequirement `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	CustomLabels         []string           `protobuf:"bytes,4,rep,name=custom_labels,json=customLabels,proto3" json:"custom_labels,omitempty"`
	ApiName              string             `protobuf:"bytes,5,opt,name=api_name,json=apiName,proto3" json:"api_name,omitempty"`
	ApiVersion           string             `protobuf:"bytes,6,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Requirement) Reset()         { *m = Requirement{} }
func (m *Requirement) String() string { return proto.CompactTextString(m) }
func (*Requirement) ProtoMessage()    {}
func (*Requirement) Descriptor() ([]byte, []int) {
	return fileDescriptor_3dda622705118f3d, []int{2}
}

func (m *Requirement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Requirement.Unmarshal(m, b)
}
func (m *Requirement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Requirement.Marshal(b, m, deterministic)
}
func (m *Requirement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Requirement.Merge(m, src)
}
func (m *Requirement) XXX_Size() int {
	return xxx_messageInfo_Requirement.Size(m)
}
func (m *Requirement) XXX_DiscardUnknown() {
	xxx_messageInfo_Requirement.DiscardUnknown(m)
}

var xxx_messageInfo_Requirement proto.InternalMessageInfo

func (m *Requirement) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Requirement) GetOperationName() string {
	if m != nil {
		return m.OperationName
	}
	return ""
}

func (m *Requirement) GetApiKey() *APIKeyRequirement {
	if m != nil {
		return m.ApiKey
	}
	return nil
}

func (m *Requirement) GetCustomLabels() []string {
	if m != nil {
		return m.CustomLabels
	}
	return nil
}

func (m *Requirement) GetApiName() string {
	if m != nil {
		return m.ApiName
	}
	return ""
}

func (m *Requirement) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*APIKey)(nil), "google.api.envoy.http.service_control.APIKey")
	proto.RegisterType((*APIKeyRequirement)(nil), "google.api.envoy.http.service_control.APIKeyRequirement")
	proto.RegisterType((*Requirement)(nil), "google.api.envoy.http.service_control.Requirement")
}

func init() {
	proto.RegisterFile("api/envoy/http/service_control/requirement.proto", fileDescriptor_3dda622705118f3d)
}

var fileDescriptor_3dda622705118f3d = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0x86, 0x6b, 0x0c, 0x06, 0xd6, 0x50, 0xa9, 0x2b, 0xb5, 0x75, 0x7b, 0xa9, 0x45, 0x85, 0xc4,
	0xa1, 0xb5, 0x5b, 0x72, 0xc9, 0x15, 0x4e, 0x44, 0x44, 0x51, 0xe2, 0x43, 0x72, 0xc8, 0xc1, 0x5a,
	0xcc, 0x08, 0x56, 0xd8, 0xde, 0x65, 0xbd, 0x36, 0xf2, 0x5b, 0xe4, 0x94, 0x87, 0xc9, 0x29, 0xaf,
	0x93, 0xb7, 0x88, 0xbc, 0x6b, 0x87, 0x28, 0xa7, 0xe4, 0xe6, 0x99, 0x7f, 0xfe, 0xf1, 0xf7, 0x8f,
	0x16, 0xfd, 0x23, 0x9c, 0xfa, 0x90, 0x16, 0xac, 0xf4, 0xb7, 0x52, 0x72, 0x3f, 0x03, 0x51, 0xd0,
	0x08, 0xc2, 0x88, 0xa5, 0x52, 0xb0, 0xd8, 0x17, 0xb0, 0xcf, 0xa9, 0x80, 0x04, 0x52, 0xe9, 0x71,
	0xc1, 0x24, 0xc3, 0xe3, 0x0d, 0x63, 0x9b, 0x18, 0x3c, 0xc2, 0xa9, 0xa7, 0x8c, 0x5e, 0x65, 0xf4,
	0xde, 0x18, 0x7f, 0x7e, 0x2f, 0x48, 0x4c, 0xd7, 0x44, 0x82, 0xdf, 0x7c, 0x68, 0xff, 0xe8, 0x16,
	0x59, 0xb3, 0xcb, 0xb3, 0x25, 0x94, 0xf8, 0x1b, 0xea, 0xec, 0x73, 0x10, 0xa5, 0x63, 0xb8, 0xc6,
	0xa4, 0xbf, 0xf8, 0x14, 0xe8, 0x12, 0x3b, 0xc8, 0xda, 0x02, 0x59, 0x83, 0x70, 0x5a, 0xb5, 0x50,
	0xd7, 0x95, 0x12, 0x31, 0xb6, 0xa3, 0xe0, 0x98, 0x8d, 0xa2, 0xeb, 0x79, 0x07, 0x99, 0x3b, 0x28,
	0x47, 0x77, 0x06, 0xfa, 0xa2, 0xb7, 0x07, 0x47, 0x70, 0xbc, 0x40, 0x3d, 0xc2, 0x69, 0xb8, 0x83,
	0x32, 0x73, 0x0c, 0xd7, 0x9c, 0xd8, 0xd3, 0xbf, 0xde, 0xbb, 0x52, 0x78, 0xf5, 0xae, 0x2e, 0xe1,
	0x74, 0x09, 0x65, 0x86, 0xff, 0xa3, 0xaf, 0x24, 0x8e, 0xd9, 0x21, 0x3c, 0x50, 0xb9, 0x65, 0xb9,
	0x0c, 0xeb, 0xbd, 0x8a, 0xb4, 0x17, 0x60, 0x25, 0xde, 0x68, 0x6d, 0xa6, 0x3c, 0xa3, 0xfb, 0x16,
	0xb2, 0x5f, 0xc3, 0xfc, 0x41, 0x83, 0xe6, 0x2f, 0x29, 0x49, 0x40, 0x87, 0x9f, 0xf7, 0x1f, 0x9e,
	0x1e, 0xcd, 0xb6, 0x68, 0xb9, 0x46, 0x60, 0xd7, 0xf2, 0x05, 0x49, 0x00, 0x8f, 0xd1, 0x67, 0xc6,
	0x41, 0x10, 0x49, 0x59, 0xaa, 0xe7, 0xd5, 0x4d, 0x82, 0xe1, 0x4b, 0x57, 0x8d, 0x5d, 0xa1, 0x6e,
	0x43, 0x52, 0x5d, 0xc6, 0x9e, 0x9e, 0x7e, 0x2c, 0xe0, 0x91, 0x2f, 0xb0, 0x74, 0x56, 0xfc, 0x1b,
	0x0d, 0xa3, 0x3c, 0x93, 0x2c, 0x09, 0x63, 0xb2, 0x82, 0x38, 0x73, 0xda, 0xae, 0x39, 0xe9, 0x07,
	0x03, 0xdd, 0x3c, 0x57, 0x3d, 0xfc, 0x43, 0x5f, 0x56, 0x81, 0x75, 0x14, 0x58, 0xc5, 0xa1, 0x90,
	0x7e, 0x21, 0xbb, 0x92, 0x0a, 0x10, 0x19, 0x65, 0xa9, 0x63, 0x29, 0x15, 0x11, 0x4e, 0xaf, 0x75,
	0x67, 0x65, 0xa9, 0xf7, 0x70, 0xf2, 0x1c, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x55, 0x92, 0xc4, 0x83,
	0x02, 0x00, 0x00,
}
