// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/envoy/http/service_control/requirement.proto

package google_api_envoy_http_service_control

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type APIKeyLocation struct {
	// Types that are valid to be assigned to Key:
	//	*APIKeyLocation_Query
	//	*APIKeyLocation_Header
	//	*APIKeyLocation_Cookie
	Key                  isAPIKeyLocation_Key `protobuf_oneof:"key"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *APIKeyLocation) Reset()         { *m = APIKeyLocation{} }
func (m *APIKeyLocation) String() string { return proto.CompactTextString(m) }
func (*APIKeyLocation) ProtoMessage()    {}
func (*APIKeyLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3dda622705118f3d, []int{0}
}

func (m *APIKeyLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIKeyLocation.Unmarshal(m, b)
}
func (m *APIKeyLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIKeyLocation.Marshal(b, m, deterministic)
}
func (m *APIKeyLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIKeyLocation.Merge(m, src)
}
func (m *APIKeyLocation) XXX_Size() int {
	return xxx_messageInfo_APIKeyLocation.Size(m)
}
func (m *APIKeyLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_APIKeyLocation.DiscardUnknown(m)
}

var xxx_messageInfo_APIKeyLocation proto.InternalMessageInfo

type isAPIKeyLocation_Key interface {
	isAPIKeyLocation_Key()
}

type APIKeyLocation_Query struct {
	Query string `protobuf:"bytes,1,opt,name=query,proto3,oneof"`
}

type APIKeyLocation_Header struct {
	Header string `protobuf:"bytes,2,opt,name=header,proto3,oneof"`
}

type APIKeyLocation_Cookie struct {
	Cookie string `protobuf:"bytes,3,opt,name=cookie,proto3,oneof"`
}

func (*APIKeyLocation_Query) isAPIKeyLocation_Key() {}

func (*APIKeyLocation_Header) isAPIKeyLocation_Key() {}

func (*APIKeyLocation_Cookie) isAPIKeyLocation_Key() {}

func (m *APIKeyLocation) GetKey() isAPIKeyLocation_Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *APIKeyLocation) GetQuery() string {
	if x, ok := m.GetKey().(*APIKeyLocation_Query); ok {
		return x.Query
	}
	return ""
}

func (m *APIKeyLocation) GetHeader() string {
	if x, ok := m.GetKey().(*APIKeyLocation_Header); ok {
		return x.Header
	}
	return ""
}

func (m *APIKeyLocation) GetCookie() string {
	if x, ok := m.GetKey().(*APIKeyLocation_Cookie); ok {
		return x.Cookie
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*APIKeyLocation) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*APIKeyLocation_Query)(nil),
		(*APIKeyLocation_Header)(nil),
		(*APIKeyLocation_Cookie)(nil),
	}
}

type APIKeyRequirement struct {
	Locations            []*APIKeyLocation `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	AllowWithoutApiKey   bool              `protobuf:"varint,2,opt,name=allow_without_api_key,json=allowWithoutApiKey,proto3" json:"allow_without_api_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *APIKeyRequirement) Reset()         { *m = APIKeyRequirement{} }
func (m *APIKeyRequirement) String() string { return proto.CompactTextString(m) }
func (*APIKeyRequirement) ProtoMessage()    {}
func (*APIKeyRequirement) Descriptor() ([]byte, []int) {
	return fileDescriptor_3dda622705118f3d, []int{1}
}

func (m *APIKeyRequirement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIKeyRequirement.Unmarshal(m, b)
}
func (m *APIKeyRequirement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIKeyRequirement.Marshal(b, m, deterministic)
}
func (m *APIKeyRequirement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIKeyRequirement.Merge(m, src)
}
func (m *APIKeyRequirement) XXX_Size() int {
	return xxx_messageInfo_APIKeyRequirement.Size(m)
}
func (m *APIKeyRequirement) XXX_DiscardUnknown() {
	xxx_messageInfo_APIKeyRequirement.DiscardUnknown(m)
}

var xxx_messageInfo_APIKeyRequirement proto.InternalMessageInfo

func (m *APIKeyRequirement) GetLocations() []*APIKeyLocation {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *APIKeyRequirement) GetAllowWithoutApiKey() bool {
	if m != nil {
		return m.AllowWithoutApiKey
	}
	return false
}

type Requirement struct {
	ServiceName          string             `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	OperationName        string             `protobuf:"bytes,2,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	ApiKey               *APIKeyRequirement `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	CustomLabels         []string           `protobuf:"bytes,4,rep,name=custom_labels,json=customLabels,proto3" json:"custom_labels,omitempty"`
	ApiName              string             `protobuf:"bytes,5,opt,name=api_name,json=apiName,proto3" json:"api_name,omitempty"`
	ApiVersion           string             `protobuf:"bytes,6,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	SkipServiceControl   bool               `protobuf:"varint,7,opt,name=skip_service_control,json=skipServiceControl,proto3" json:"skip_service_control,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Requirement) Reset()         { *m = Requirement{} }
func (m *Requirement) String() string { return proto.CompactTextString(m) }
func (*Requirement) ProtoMessage()    {}
func (*Requirement) Descriptor() ([]byte, []int) {
	return fileDescriptor_3dda622705118f3d, []int{2}
}

func (m *Requirement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Requirement.Unmarshal(m, b)
}
func (m *Requirement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Requirement.Marshal(b, m, deterministic)
}
func (m *Requirement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Requirement.Merge(m, src)
}
func (m *Requirement) XXX_Size() int {
	return xxx_messageInfo_Requirement.Size(m)
}
func (m *Requirement) XXX_DiscardUnknown() {
	xxx_messageInfo_Requirement.DiscardUnknown(m)
}

var xxx_messageInfo_Requirement proto.InternalMessageInfo

func (m *Requirement) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Requirement) GetOperationName() string {
	if m != nil {
		return m.OperationName
	}
	return ""
}

func (m *Requirement) GetApiKey() *APIKeyRequirement {
	if m != nil {
		return m.ApiKey
	}
	return nil
}

func (m *Requirement) GetCustomLabels() []string {
	if m != nil {
		return m.CustomLabels
	}
	return nil
}

func (m *Requirement) GetApiName() string {
	if m != nil {
		return m.ApiName
	}
	return ""
}

func (m *Requirement) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *Requirement) GetSkipServiceControl() bool {
	if m != nil {
		return m.SkipServiceControl
	}
	return false
}

func init() {
	proto.RegisterType((*APIKeyLocation)(nil), "google.api.envoy.http.service_control.APIKeyLocation")
	proto.RegisterType((*APIKeyRequirement)(nil), "google.api.envoy.http.service_control.APIKeyRequirement")
	proto.RegisterType((*Requirement)(nil), "google.api.envoy.http.service_control.Requirement")
}

func init() {
	proto.RegisterFile("api/envoy/http/service_control/requirement.proto", fileDescriptor_3dda622705118f3d)
}

var fileDescriptor_3dda622705118f3d = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x80, 0x71, 0xdc, 0xa4, 0xcd, 0xb8, 0xad, 0xc4, 0x8a, 0x9f, 0x85, 0x0b, 0x51, 0x10, 0x52,
	0x0e, 0xc8, 0x0e, 0x45, 0x48, 0x5c, 0x5b, 0x2e, 0xa0, 0x56, 0x08, 0xb6, 0x12, 0x1c, 0xad, 0xad,
	0x3b, 0x6a, 0x56, 0xd9, 0x78, 0xb6, 0xeb, 0x4d, 0x2a, 0x3f, 0x0b, 0x6f, 0xc2, 0x89, 0x77, 0xe0,
	0x29, 0x78, 0x0b, 0xb4, 0xbb, 0x36, 0x2d, 0x39, 0xc1, 0xcd, 0x33, 0xdf, 0x8c, 0xe7, 0x9b, 0xd1,
	0xc2, 0x5c, 0x1a, 0x55, 0x60, 0xbd, 0xa1, 0xb6, 0x58, 0x38, 0x67, 0x8a, 0x06, 0xed, 0x46, 0x55,
	0x58, 0x56, 0x54, 0x3b, 0x4b, 0xba, 0xb0, 0x78, 0xbd, 0x56, 0x16, 0x57, 0x58, 0xbb, 0xdc, 0x58,
	0x72, 0xc4, 0x5e, 0x5c, 0x11, 0x5d, 0x69, 0xcc, 0xa5, 0x51, 0x79, 0x68, 0xcc, 0x7d, 0x63, 0xbe,
	0xd5, 0xf8, 0xf4, 0xf1, 0x46, 0x6a, 0x75, 0x29, 0x1d, 0x16, 0xfd, 0x47, 0xec, 0x9f, 0x56, 0x70,
	0x78, 0xfc, 0xe9, 0xc3, 0x29, 0xb6, 0x67, 0x54, 0x49, 0xa7, 0xa8, 0x66, 0x8f, 0x60, 0x78, 0xbd,
	0x46, 0xdb, 0xf2, 0x64, 0x92, 0xcc, 0xc6, 0xef, 0xef, 0x89, 0x18, 0x32, 0x0e, 0xa3, 0x05, 0xca,
	0x4b, 0xb4, 0x7c, 0xd0, 0x81, 0x2e, 0xf6, 0xa4, 0x22, 0x5a, 0x2a, 0xe4, 0x69, 0x4f, 0x62, 0x7c,
	0x32, 0x84, 0x74, 0x89, 0xed, 0xf4, 0x5b, 0x02, 0xf7, 0xe3, 0x14, 0x71, 0xbb, 0x00, 0x3b, 0x87,
	0xb1, 0xee, 0x86, 0x36, 0x3c, 0x99, 0xa4, 0xb3, 0xec, 0xe8, 0x4d, 0xfe, 0x4f, 0xeb, 0xe4, 0x7f,
	0x2b, 0x8b, 0xdb, 0xff, 0xb0, 0x57, 0xf0, 0x50, 0x6a, 0x4d, 0x37, 0xe5, 0x8d, 0x72, 0x0b, 0x5a,
	0xbb, 0x52, 0x1a, 0x55, 0x2e, 0xb1, 0x0d, 0xd2, 0x7b, 0x82, 0x05, 0xf8, 0x35, 0xb2, 0x63, 0xa3,
	0x4e, 0xb1, 0x9d, 0xfe, 0x1c, 0x40, 0x76, 0xd7, 0xeb, 0x25, 0xec, 0xf7, 0xf3, 0x6a, 0xb9, 0xc2,
	0x78, 0x87, 0x93, 0xf1, 0xf7, 0x5f, 0x3f, 0xd2, 0x1d, 0x3b, 0x98, 0x24, 0x22, 0xeb, 0xf0, 0x47,
	0xb9, 0x42, 0x36, 0x87, 0x43, 0x32, 0x68, 0xc3, 0xf8, 0x58, 0x3f, 0xd8, 0xae, 0x3f, 0xf8, 0x53,
	0x10, 0x3a, 0x3e, 0xc3, 0x6e, 0x2f, 0xe5, 0xef, 0x95, 0x1d, 0xbd, 0xfd, 0xaf, 0xad, 0xef, 0xa8,
	0x8a, 0x91, 0x0c, 0x2b, 0xb0, 0xe7, 0x70, 0x50, 0xad, 0x1b, 0x47, 0xab, 0x52, 0xcb, 0x0b, 0xd4,
	0x0d, 0xdf, 0x99, 0xa4, 0xb3, 0xb1, 0xd8, 0x8f, 0xc9, 0xb3, 0x90, 0x63, 0x4f, 0x60, 0xcf, 0xcf,
	0x0d, 0x8e, 0x43, 0xef, 0x28, 0xbc, 0x47, 0x50, 0x7a, 0x06, 0x99, 0x47, 0x1b, 0xb4, 0x8d, 0xa2,
	0x9a, 0x8f, 0x02, 0x05, 0x69, 0xd4, 0x97, 0x98, 0x61, 0x73, 0x78, 0xd0, 0x2c, 0x95, 0x29, 0xb7,
	0x94, 0xf8, 0x6e, 0xbc, 0xaa, 0x67, 0xe7, 0x11, 0xbd, 0x8b, 0xe4, 0x62, 0x14, 0xde, 0xd7, 0xeb,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x62, 0xe6, 0x38, 0x8a, 0xd3, 0x02, 0x00, 0x00,
}
