// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/agent/agent_service.proto

package agent

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetAccessTokenRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenRequest) Reset()         { *m = GetAccessTokenRequest{} }
func (m *GetAccessTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenRequest) ProtoMessage()    {}
func (*GetAccessTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8df36f2ea325fad, []int{0}
}

func (m *GetAccessTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenRequest.Unmarshal(m, b)
}
func (m *GetAccessTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetAccessTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenRequest.Merge(m, src)
}
func (m *GetAccessTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenRequest.Size(m)
}
func (m *GetAccessTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenRequest proto.InternalMessageInfo

type GetAccessTokenResponse struct {
	AccessToken          string             `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresIn            *duration.Duration `protobuf:"bytes,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetAccessTokenResponse) Reset()         { *m = GetAccessTokenResponse{} }
func (m *GetAccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenResponse) ProtoMessage()    {}
func (*GetAccessTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8df36f2ea325fad, []int{1}
}

func (m *GetAccessTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenResponse.Unmarshal(m, b)
}
func (m *GetAccessTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetAccessTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenResponse.Merge(m, src)
}
func (m *GetAccessTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenResponse.Size(m)
}
func (m *GetAccessTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenResponse proto.InternalMessageInfo

func (m *GetAccessTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetAccessTokenResponse) GetExpiresIn() *duration.Duration {
	if m != nil {
		return m.ExpiresIn
	}
	return nil
}

func init() {
	proto.RegisterType((*GetAccessTokenRequest)(nil), "google.api_proxy.agent.GetAccessTokenRequest")
	proto.RegisterType((*GetAccessTokenResponse)(nil), "google.api_proxy.agent.GetAccessTokenResponse")
}

func init() { proto.RegisterFile("api/agent/agent_service.proto", fileDescriptor_c8df36f2ea325fad) }

var fileDescriptor_c8df36f2ea325fad = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0x47, 0x0d, 0x88, 0xd0, 0x69, 0xf1, 0x10, 0xb0, 0xd6, 0x82, 0x52, 0xf7, 0xd4, 0x8b, 0xb3,
	0x50, 0x2f, 0x5e, 0x0b, 0x82, 0x78, 0x5d, 0xbd, 0x87, 0x74, 0x1d, 0x97, 0xa0, 0x64, 0xd2, 0xfc,
	0x91, 0x7a, 0xf4, 0x9b, 0x4b, 0x93, 0x15, 0x51, 0xf6, 0xd0, 0x4b, 0x0e, 0xbf, 0xbc, 0x81, 0xf7,
	0xe0, 0x52, 0x3b, 0x53, 0xeb, 0x8e, 0x6c, 0x2c, 0xaf, 0x0a, 0xe4, 0x3f, 0x4c, 0x4b, 0xe8, 0x3c,
	0x47, 0x96, 0xd3, 0x8e, 0xb9, 0x7b, 0x27, 0xd4, 0xce, 0x28, 0xe7, 0x79, 0xf7, 0x89, 0x99, 0x9a,
	0x5f, 0x95, 0xbd, 0xce, 0xd4, 0x26, 0xbd, 0xd6, 0x2f, 0xc9, 0xeb, 0x68, 0xd8, 0x96, 0xbb, 0xea,
	0x1c, 0xce, 0x1e, 0x28, 0xae, 0xdb, 0x96, 0x42, 0x78, 0xe6, 0x37, 0xb2, 0x0d, 0x6d, 0x13, 0x85,
	0x58, 0x25, 0x98, 0xfe, 0xff, 0x08, 0x8e, 0x6d, 0x20, 0x79, 0x0d, 0x13, 0x9d, 0x67, 0x15, 0xf7,
	0xfb, 0x4c, 0x2c, 0xc4, 0x72, 0xd4, 0x8c, 0xf5, 0x2f, 0x2a, 0xef, 0x00, 0x68, 0xe7, 0x8c, 0xa7,
	0xa0, 0x8c, 0x9d, 0x1d, 0x2f, 0xc4, 0x72, 0xbc, 0xba, 0xc0, 0x5e, 0xf1, 0x47, 0x05, 0xef, 0x7b,
	0x95, 0x66, 0xd4, 0xc3, 0x8f, 0x76, 0xf5, 0x25, 0x60, 0xb2, 0xde, 0x9b, 0x3f, 0x95, 0x3c, 0xb9,
	0x85, 0xd3, 0xbf, 0x1e, 0xf2, 0x06, 0x87, 0x5b, 0x71, 0x30, 0x64, 0x8e, 0x87, 0xe2, 0x25, 0xaf,
	0x3a, 0xda, 0x9c, 0x64, 0xc3, 0xdb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xdc, 0xea, 0x81,
	0x73, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentServiceClient interface {
	GetAccessToken(ctx context.Context, in *GetAccessTokenRequest, opts ...grpc.CallOption) (*GetAccessTokenResponse, error)
}

type agentServiceClient struct {
	cc *grpc.ClientConn
}

func NewAgentServiceClient(cc *grpc.ClientConn) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) GetAccessToken(ctx context.Context, in *GetAccessTokenRequest, opts ...grpc.CallOption) (*GetAccessTokenResponse, error) {
	out := new(GetAccessTokenResponse)
	err := c.cc.Invoke(ctx, "/google.api_proxy.agent.AgentService/GetAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
type AgentServiceServer interface {
	GetAccessToken(context.Context, *GetAccessTokenRequest) (*GetAccessTokenResponse, error)
}

func RegisterAgentServiceServer(s *grpc.Server, srv AgentServiceServer) {
	s.RegisterService(&_AgentService_serviceDesc, srv)
}

func _AgentService_GetAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.api_proxy.agent.AgentService/GetAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAccessToken(ctx, req.(*GetAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.api_proxy.agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccessToken",
			Handler:    _AgentService_GetAccessToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/agent/agent_service.proto",
}
