// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/agent/agent_service.proto

package google_api_proxy_agent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAccessTokenRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenRequest) Reset()         { *m = GetAccessTokenRequest{} }
func (m *GetAccessTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenRequest) ProtoMessage()    {}
func (*GetAccessTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8df36f2ea325fad, []int{0}
}

func (m *GetAccessTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenRequest.Unmarshal(m, b)
}
func (m *GetAccessTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetAccessTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenRequest.Merge(m, src)
}
func (m *GetAccessTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenRequest.Size(m)
}
func (m *GetAccessTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenRequest proto.InternalMessageInfo

type GetIdentityJWTTokenRequest struct {
	Audience             string   `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIdentityJWTTokenRequest) Reset()         { *m = GetIdentityJWTTokenRequest{} }
func (m *GetIdentityJWTTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetIdentityJWTTokenRequest) ProtoMessage()    {}
func (*GetIdentityJWTTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8df36f2ea325fad, []int{1}
}

func (m *GetIdentityJWTTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIdentityJWTTokenRequest.Unmarshal(m, b)
}
func (m *GetIdentityJWTTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIdentityJWTTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetIdentityJWTTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIdentityJWTTokenRequest.Merge(m, src)
}
func (m *GetIdentityJWTTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetIdentityJWTTokenRequest.Size(m)
}
func (m *GetIdentityJWTTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIdentityJWTTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIdentityJWTTokenRequest proto.InternalMessageInfo

func (m *GetIdentityJWTTokenRequest) GetAudience() string {
	if m != nil {
		return m.Audience
	}
	return ""
}

type GetTokenResponse struct {
	AccessToken          string             `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresIn            *duration.Duration `protobuf:"bytes,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetTokenResponse) Reset()         { *m = GetTokenResponse{} }
func (m *GetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenResponse) ProtoMessage()    {}
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8df36f2ea325fad, []int{2}
}

func (m *GetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenResponse.Unmarshal(m, b)
}
func (m *GetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResponse.Merge(m, src)
}
func (m *GetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenResponse.Size(m)
}
func (m *GetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResponse proto.InternalMessageInfo

func (m *GetTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetTokenResponse) GetExpiresIn() *duration.Duration {
	if m != nil {
		return m.ExpiresIn
	}
	return nil
}

func init() {
	proto.RegisterType((*GetAccessTokenRequest)(nil), "google.api_proxy.agent.GetAccessTokenRequest")
	proto.RegisterType((*GetIdentityJWTTokenRequest)(nil), "google.api_proxy.agent.GetIdentityJWTTokenRequest")
	proto.RegisterType((*GetTokenResponse)(nil), "google.api_proxy.agent.GetTokenResponse")
}

func init() { proto.RegisterFile("api/agent/agent_service.proto", fileDescriptor_c8df36f2ea325fad) }

var fileDescriptor_c8df36f2ea325fad = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x8d, 0x82, 0xb8, 0xb7, 0x21, 0x12, 0x51, 0x67, 0x41, 0x99, 0x3d, 0xf5, 0x62, 0x0a,
	0xf5, 0xb2, 0xeb, 0x44, 0x28, 0xf3, 0x58, 0x07, 0x1e, 0x4b, 0xd6, 0x3e, 0x4b, 0x98, 0x24, 0xb1,
	0x79, 0x95, 0xed, 0xe6, 0xdf, 0xec, 0x5f, 0x20, 0x6b, 0xeb, 0x8f, 0x41, 0x1d, 0xec, 0x12, 0xc8,
	0xcb, 0xf7, 0xe5, 0xbd, 0xcf, 0x07, 0xae, 0xa4, 0x55, 0xa1, 0x2c, 0x50, 0x53, 0x73, 0xa6, 0x0e,
	0xcb, 0x77, 0x95, 0xa1, 0xb0, 0xa5, 0x21, 0xc3, 0xcf, 0x0b, 0x63, 0x8a, 0x57, 0x14, 0xd2, 0xaa,
	0xd4, 0x96, 0x66, 0xb9, 0x12, 0x75, 0xca, 0xbb, 0x6e, 0xea, 0x61, 0x9d, 0x9a, 0x57, 0x2f, 0x61,
	0x5e, 0x95, 0x92, 0x94, 0xd1, 0x4d, 0x9f, 0x7f, 0x01, 0x67, 0x31, 0xd2, 0x24, 0xcb, 0xd0, 0xb9,
	0x99, 0x59, 0xa0, 0x4e, 0xf0, 0xad, 0x42, 0x47, 0xfe, 0x18, 0xbc, 0x18, 0x69, 0x9a, 0xa3, 0x26,
	0x45, 0xab, 0xc7, 0xe7, 0xd9, 0xdf, 0x57, 0xee, 0xc1, 0x91, 0xac, 0x72, 0x85, 0x3a, 0xc3, 0x21,
	0x1b, 0xb1, 0xa0, 0x97, 0xfc, 0xdc, 0x7d, 0x03, 0x27, 0x31, 0x52, 0x1b, 0x77, 0xd6, 0x68, 0x87,
	0xfc, 0x06, 0x06, 0xb2, 0x9e, 0x91, 0xd2, 0xba, 0xde, 0xf6, 0xf4, 0xe5, 0xef, 0x5c, 0x3e, 0x06,
	0xc0, 0xa5, 0x55, 0x25, 0xba, 0x54, 0xe9, 0xe1, 0xfe, 0x88, 0x05, 0xfd, 0xe8, 0x52, 0xb4, 0x58,
	0xdf, 0xeb, 0x8b, 0x87, 0x76, 0xfd, 0xa4, 0xd7, 0x86, 0xa7, 0x3a, 0xfa, 0x64, 0x30, 0x98, 0xac,
	0x69, 0x9f, 0x1a, 0x25, 0x7c, 0x01, 0xc7, 0x9b, 0x50, 0xfc, 0x56, 0x74, 0xfb, 0x11, 0x9d, 0xf0,
	0x5e, 0xb0, 0x25, 0xbe, 0x01, 0xe6, 0xef, 0xf1, 0x0a, 0x4e, 0x3b, 0x44, 0xf1, 0x68, 0xcb, 0x17,
	0xff, 0x58, 0xdd, 0x65, 0xec, 0xfd, 0xc1, 0x07, 0x63, 0xf3, 0xc3, 0xda, 0xcb, 0xdd, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb3, 0xe2, 0x9d, 0xd3, 0x1d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentServiceClient interface {
	GetAccessToken(ctx context.Context, in *GetAccessTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
	GetIdentityJWTToken(ctx context.Context, in *GetIdentityJWTTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
}

type agentServiceClient struct {
	cc *grpc.ClientConn
}

func NewAgentServiceClient(cc *grpc.ClientConn) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) GetAccessToken(ctx context.Context, in *GetAccessTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, "/google.api_proxy.agent.AgentService/GetAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetIdentityJWTToken(ctx context.Context, in *GetIdentityJWTTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, "/google.api_proxy.agent.AgentService/GetIdentityJWTToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
type AgentServiceServer interface {
	GetAccessToken(context.Context, *GetAccessTokenRequest) (*GetTokenResponse, error)
	GetIdentityJWTToken(context.Context, *GetIdentityJWTTokenRequest) (*GetTokenResponse, error)
}

func RegisterAgentServiceServer(s *grpc.Server, srv AgentServiceServer) {
	s.RegisterService(&_AgentService_serviceDesc, srv)
}

func _AgentService_GetAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.api_proxy.agent.AgentService/GetAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAccessToken(ctx, req.(*GetAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetIdentityJWTToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityJWTTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetIdentityJWTToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.api_proxy.agent.AgentService/GetIdentityJWTToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetIdentityJWTToken(ctx, req.(*GetIdentityJWTTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.api_proxy.agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccessToken",
			Handler:    _AgentService_GetAccessToken_Handler,
		},
		{
			MethodName: "GetIdentityJWTToken",
			Handler:    _AgentService_GetIdentityJWTToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/agent/agent_service.proto",
}
