# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM debian:buster
LABEL maintainer="jilinxia@google.com"

# add env we can debug with the image name:tag
ARG IMAGE_ARG
ENV IMAGE=${IMAGE_ARG}


RUN apt-get update -y
RUN apt-get -y install \
    wget make cmake python python-pip pkg-config coreutils \
    zlib1g-dev curl libtool automake zip time rsync ninja-build \
    git bash-completion jq default-jdk python3-distutils libicu-dev


# install nodejs, which is needed for integration tests
RUN sh -c 'curl -sL https://deb.nodesource.com/setup_12.x | bash -'
RUN apt-get install -y nodejs

# install bazel
RUN INSTALLER="bazel-0.28.1-installer-linux-x86_64.sh"; \
    DOWNLOAD_URL="https://github.com/bazelbuild/bazel/releases/download/0.28.1/${INSTALLER}"; \
    wget -q "${DOWNLOAD_URL}" && \
    chmod +x "${INSTALLER}" && "./${INSTALLER}" && rm "${INSTALLER}"

# install Bazelisk
RUN wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v0.0.8/bazelisk-linux-amd64 && \
    chmod +x /usr/local/bin/bazel

# install clang-10 and associated tools (new envoy)
RUN wget -O- https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add - && \
    echo "deb https://apt.llvm.org/buster/ llvm-toolchain-buster-10 main" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y llvm-10 llvm-10-dev libclang-10-dev clang-10 \
        lld-10 clang-tools-10 clang-format-10 libc++-dev xz-utils lcov

ENV CC clang-10
ENV CXX clang++-10

# install golang and setup Go standard envs
ENV GOPATH /go
ENV PATH /usr/local/go/bin:$PATH
ENV PATH $GOPATH/bin:$PATH

ENV GO_TARBALL "go1.13.linux-amd64.tar.gz"
RUN wget -q "https://storage.googleapis.com/golang/${GO_TARBALL}" && \
    tar xzf "${GO_TARBALL}" -C /usr/local && \
    rm "${GO_TARBALL}"

# Install buildifier
RUN go get github.com/bazelbuild/buildtools/buildifier

# install gcloud package
RUN curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz
RUN mkdir -p /usr/local/gcloud \
  && tar -C /usr/local/gcloud -xvf /tmp/google-cloud-sdk.tar.gz \
  && /usr/local/gcloud/google-cloud-sdk/install.sh
ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin

# For Cloud Run
RUN gcloud components install beta --quiet