# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM debian:bookworm
LABEL maintainer="esp-eng@google.com"

# add env we can debug with the image name:tag
ARG IMAGE_ARG
ENV IMAGE=${IMAGE_ARG}

RUN apt-get update -y && apt-get -y install \
    wget make cmake python3 python3-pip python3-venv pkg-config coreutils \
    zlib1g-dev curl libtool automake zip time rsync ninja-build \
    git bash-completion jq default-jdk libicu-dev libbrotli-dev \
    gpg lsb-release

# install nodejs, which is needed for integration tests
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs

# install Bazelisk
RUN wget -O /usr/local/bin/bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-linux-amd64 && \
    chmod +x /usr/local/bin/bazelisk

# install clang-14 and associated tools (new envoy)
RUN apt-get update && \
    apt-get install -y llvm-14 llvm-14-dev libclang-14-dev clang-14 \
        lld-14 clang-tools-14 clang-format-14 libc++-dev xz-utils libclang-rt-14-dev


ENV CC clang-14
ENV CXX clang++-14

# install golang and setup Go standard envs
ENV GOPATH /go
ENV PATH /usr/local/go/bin:$PATH
ENV PATH $GOPATH/bin:$PATH

ENV GO_TARBALL "go1.26.6.linux-amd64.tar.gz"
RUN wget -q "https://go.dev/dl/${GO_TARBALL}" && \
    tar xzf "${GO_TARBALL}" -C /usr/local && \
    rm "${GO_TARBALL}" && \
    echo 'export PATH=/usr/local/go/bin:/go/bin:$PATH' > /etc/profile.d/go.sh && \
    git config --system --add safe.directory '*'

# Install buildifier
RUN go install github.com/bazelbuild/buildtools/buildifier@latest

RUN pip install --break-system-packages pipx && \
    pipx install beautysh

# install gcloud package
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg && \
    apt-get update && apt-get install -y google-cloud-cli


