# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM _ENVOY_IMAGE_SHA_NAME

# Install python3
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

ENV PATH /bin:$PATH

ADD docker/generic/* /apiproxy/
ADD bin/bootstrap /bin/
ADD bin/configmanager /bin/

# create envoy user and group
RUN groupadd -g 999 envoy && useradd -r -u 999 -g envoy envoy
# run as user envoy
USER envoy

ENTRYPOINT ["python3", "/apiproxy/start_proxy.py"]
