# Copyright 2018 Google Cloud Platform Proxy Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:latest

ARG SERVICE_NAME
ARG CONFIG_ID

ADD scripts/start_proxy.sh start_proxy.sh

ADD scripts/envoy_bootstrap_v2_startup.yaml startup.yaml

ADD vendor/configmanager configmanager

ADD vendor/envoy envoy

ENTRYPOINT ["./start_proxy.sh"]
CMD ["echo $SERVICE_NAME", "echo $CONFIG_ID"]
