# Copyright 2018 Google Cloud Platform Proxy Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM python:3.6-buster

ENV PATH /bin:$PATH

ADD docker/generic/* apiproxy/
ADD bin/* apiproxy/

# Stackdriver is using grpc call. It needs its roots.pem at /usr/share/grpc
RUN mkdir -p /usr/share/grpc && cp apiproxy/grpc_roots.pem /usr/share/grpc/

# create envoy user and group
RUN groupadd -g 999 envoy && useradd -r -u 999 -g envoy envoy

# run as user envoy
USER envoy

ENTRYPOINT ["python", "apiproxy/start_proxy.py"]
