// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/envoy/http/backend_auth/config.proto

package google_api_envoy_http_backend_auth

import (
	common "cloudesf.googlesource.com/gcpproxy/src/go/proto/api/envoy/http/common"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BackendAuthRule struct {
	Operation            string   `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	JwtAudience          string   `protobuf:"bytes,2,opt,name=jwt_audience,json=jwtAudience,proto3" json:"jwt_audience,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendAuthRule) Reset()         { *m = BackendAuthRule{} }
func (m *BackendAuthRule) String() string { return proto.CompactTextString(m) }
func (*BackendAuthRule) ProtoMessage()    {}
func (*BackendAuthRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_f545d61a25950416, []int{0}
}

func (m *BackendAuthRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendAuthRule.Unmarshal(m, b)
}
func (m *BackendAuthRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendAuthRule.Marshal(b, m, deterministic)
}
func (m *BackendAuthRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendAuthRule.Merge(m, src)
}
func (m *BackendAuthRule) XXX_Size() int {
	return xxx_messageInfo_BackendAuthRule.Size(m)
}
func (m *BackendAuthRule) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendAuthRule.DiscardUnknown(m)
}

var xxx_messageInfo_BackendAuthRule proto.InternalMessageInfo

func (m *BackendAuthRule) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *BackendAuthRule) GetJwtAudience() string {
	if m != nil {
		return m.JwtAudience
	}
	return ""
}

type FilterConfig struct {
	Rules                []*BackendAuthRule  `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	AccessToken          *common.AccessToken `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *FilterConfig) Reset()         { *m = FilterConfig{} }
func (m *FilterConfig) String() string { return proto.CompactTextString(m) }
func (*FilterConfig) ProtoMessage()    {}
func (*FilterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f545d61a25950416, []int{1}
}

func (m *FilterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterConfig.Unmarshal(m, b)
}
func (m *FilterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterConfig.Marshal(b, m, deterministic)
}
func (m *FilterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterConfig.Merge(m, src)
}
func (m *FilterConfig) XXX_Size() int {
	return xxx_messageInfo_FilterConfig.Size(m)
}
func (m *FilterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FilterConfig proto.InternalMessageInfo

func (m *FilterConfig) GetRules() []*BackendAuthRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *FilterConfig) GetAccessToken() *common.AccessToken {
	if m != nil {
		return m.AccessToken
	}
	return nil
}

func init() {
	proto.RegisterType((*BackendAuthRule)(nil), "google.api.envoy.http.backend_auth.BackendAuthRule")
	proto.RegisterType((*FilterConfig)(nil), "google.api.envoy.http.backend_auth.FilterConfig")
}

func init() {
	proto.RegisterFile("api/envoy/http/backend_auth/config.proto", fileDescriptor_f545d61a25950416)
}

var fileDescriptor_f545d61a25950416 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0xc7, 0x49, 0xfb, 0x7d, 0x42, 0x37, 0x01, 0x21, 0x17, 0x43, 0x4f, 0x21, 0x17, 0x23, 0xc8,
	0x2e, 0xb4, 0x4f, 0x90, 0x0a, 0x82, 0xe0, 0x29, 0x78, 0x0f, 0x93, 0xcd, 0x98, 0x6c, 0x9b, 0xee,
	0x84, 0x64, 0xd2, 0xe2, 0x13, 0xf9, 0x0e, 0x9e, 0x7c, 0x1d, 0xdf, 0x42, 0x9a, 0x28, 0x95, 0x80,
	0x78, 0xdb, 0xe5, 0x3f, 0xbf, 0x1f, 0x33, 0x7f, 0x11, 0x43, 0x63, 0x14, 0xda, 0x03, 0xbd, 0xa8,
	0x8a, 0xb9, 0x51, 0x39, 0xe8, 0x1d, 0xda, 0x22, 0x83, 0x9e, 0x2b, 0xa5, 0xc9, 0x3e, 0x9b, 0x52,
	0x36, 0x2d, 0x31, 0xf9, 0x51, 0x49, 0x54, 0xd6, 0x28, 0xa1, 0x31, 0x72, 0x00, 0xe4, 0x09, 0x90,
	0x3f, 0x81, 0x65, 0x38, 0xb1, 0x69, 0xda, 0xef, 0xc9, 0xaa, 0x1c, 0x3a, 0x1c, 0x2d, 0xcb, 0xab,
	0x03, 0xd4, 0xa6, 0x00, 0x46, 0xf5, 0xfd, 0x18, 0x83, 0xa8, 0x12, 0x97, 0x9b, 0x51, 0x95, 0xf4,
	0x5c, 0xa5, 0x7d, 0x8d, 0xfe, 0xb5, 0x58, 0x50, 0x83, 0x2d, 0xb0, 0x21, 0x1b, 0x38, 0xa1, 0x13,
	0x2f, 0x36, 0x8b, 0xb7, 0x8f, 0xf7, 0xf9, 0xbf, 0x76, 0x16, 0x3a, 0xe9, 0x39, 0xf3, 0x6f, 0x85,
	0xb7, 0x3d, 0x72, 0x06, 0x7d, 0x61, 0xd0, 0x6a, 0x0c, 0x66, 0xd3, 0x59, 0x77, 0x7b, 0xe4, 0xe4,
	0x2b, 0x8d, 0x5e, 0x1d, 0xe1, 0xdd, 0x9b, 0x9a, 0xb1, 0xbd, 0x1b, 0xee, 0xf3, 0x1f, 0xc4, 0xff,
	0xb6, 0xaf, 0xb1, 0x0b, 0x9c, 0x70, 0x1e, 0xbb, 0xab, 0xb5, 0xfc, 0xfb, 0x52, 0x39, 0xd9, 0x35,
	0x1d, 0x0d, 0xfe, 0xa3, 0xf0, 0x40, 0x6b, 0xec, 0xba, 0x8c, 0x69, 0x87, 0x76, 0xd8, 0xc4, 0x5d,
	0xdd, 0xfc, 0x62, 0x1c, 0xeb, 0x91, 0xc9, 0x40, 0x3c, 0x9d, 0x80, 0xd4, 0x85, 0xf3, 0x27, 0xbf,
	0x18, 0xaa, 0x59, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x39, 0xac, 0x95, 0xa5, 0x01, 0x00,
	0x00,
}
