// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/envoy/http/common/base.proto

package google_api_envoy_http_common

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pattern struct {
	UriTemplate          string   `protobuf:"bytes,1,opt,name=uri_template,json=uriTemplate,proto3" json:"uri_template,omitempty"`
	HttpMethod           string   `protobuf:"bytes,2,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pattern) Reset()         { *m = Pattern{} }
func (m *Pattern) String() string { return proto.CompactTextString(m) }
func (*Pattern) ProtoMessage()    {}
func (*Pattern) Descriptor() ([]byte, []int) {
	return fileDescriptor_714cdd8deafbad4d, []int{0}
}

func (m *Pattern) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pattern.Unmarshal(m, b)
}
func (m *Pattern) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pattern.Marshal(b, m, deterministic)
}
func (m *Pattern) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pattern.Merge(m, src)
}
func (m *Pattern) XXX_Size() int {
	return xxx_messageInfo_Pattern.Size(m)
}
func (m *Pattern) XXX_DiscardUnknown() {
	xxx_messageInfo_Pattern.DiscardUnknown(m)
}

var xxx_messageInfo_Pattern proto.InternalMessageInfo

func (m *Pattern) GetUriTemplate() string {
	if m != nil {
		return m.UriTemplate
	}
	return ""
}

func (m *Pattern) GetHttpMethod() string {
	if m != nil {
		return m.HttpMethod
	}
	return ""
}

type HttpUri struct {
	Uri                  string             `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Cluster              string             `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Timeout              *duration.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *HttpUri) Reset()         { *m = HttpUri{} }
func (m *HttpUri) String() string { return proto.CompactTextString(m) }
func (*HttpUri) ProtoMessage()    {}
func (*HttpUri) Descriptor() ([]byte, []int) {
	return fileDescriptor_714cdd8deafbad4d, []int{1}
}

func (m *HttpUri) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpUri.Unmarshal(m, b)
}
func (m *HttpUri) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpUri.Marshal(b, m, deterministic)
}
func (m *HttpUri) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpUri.Merge(m, src)
}
func (m *HttpUri) XXX_Size() int {
	return xxx_messageInfo_HttpUri.Size(m)
}
func (m *HttpUri) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpUri.DiscardUnknown(m)
}

var xxx_messageInfo_HttpUri proto.InternalMessageInfo

func (m *HttpUri) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *HttpUri) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *HttpUri) GetTimeout() *duration.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

type DataSource struct {
	// Types that are valid to be assigned to Specifier:
	//	*DataSource_Filename
	//	*DataSource_InlineString
	Specifier            isDataSource_Specifier `protobuf_oneof:"specifier"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DataSource) Reset()         { *m = DataSource{} }
func (m *DataSource) String() string { return proto.CompactTextString(m) }
func (*DataSource) ProtoMessage()    {}
func (*DataSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_714cdd8deafbad4d, []int{2}
}

func (m *DataSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSource.Unmarshal(m, b)
}
func (m *DataSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSource.Marshal(b, m, deterministic)
}
func (m *DataSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSource.Merge(m, src)
}
func (m *DataSource) XXX_Size() int {
	return xxx_messageInfo_DataSource.Size(m)
}
func (m *DataSource) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSource.DiscardUnknown(m)
}

var xxx_messageInfo_DataSource proto.InternalMessageInfo

type isDataSource_Specifier interface {
	isDataSource_Specifier()
}

type DataSource_Filename struct {
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3,oneof"`
}

type DataSource_InlineString struct {
	InlineString string `protobuf:"bytes,2,opt,name=inline_string,json=inlineString,proto3,oneof"`
}

func (*DataSource_Filename) isDataSource_Specifier() {}

func (*DataSource_InlineString) isDataSource_Specifier() {}

func (m *DataSource) GetSpecifier() isDataSource_Specifier {
	if m != nil {
		return m.Specifier
	}
	return nil
}

func (m *DataSource) GetFilename() string {
	if x, ok := m.GetSpecifier().(*DataSource_Filename); ok {
		return x.Filename
	}
	return ""
}

func (m *DataSource) GetInlineString() string {
	if x, ok := m.GetSpecifier().(*DataSource_InlineString); ok {
		return x.InlineString
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DataSource) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DataSource_Filename)(nil),
		(*DataSource_InlineString)(nil),
	}
}

type AccessToken struct {
	// Types that are valid to be assigned to TokenType:
	//	*AccessToken_RemoteToken
	//	*AccessToken_ServiceAccountSecret
	TokenType            isAccessToken_TokenType `protobuf_oneof:"token_type"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *AccessToken) Reset()         { *m = AccessToken{} }
func (m *AccessToken) String() string { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()    {}
func (*AccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_714cdd8deafbad4d, []int{3}
}

func (m *AccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessToken.Unmarshal(m, b)
}
func (m *AccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessToken.Marshal(b, m, deterministic)
}
func (m *AccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessToken.Merge(m, src)
}
func (m *AccessToken) XXX_Size() int {
	return xxx_messageInfo_AccessToken.Size(m)
}
func (m *AccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_AccessToken proto.InternalMessageInfo

type isAccessToken_TokenType interface {
	isAccessToken_TokenType()
}

type AccessToken_RemoteToken struct {
	RemoteToken *HttpUri `protobuf:"bytes,1,opt,name=remote_token,json=remoteToken,proto3,oneof"`
}

type AccessToken_ServiceAccountSecret struct {
	ServiceAccountSecret *DataSource `protobuf:"bytes,2,opt,name=service_account_secret,json=serviceAccountSecret,proto3,oneof"`
}

func (*AccessToken_RemoteToken) isAccessToken_TokenType() {}

func (*AccessToken_ServiceAccountSecret) isAccessToken_TokenType() {}

func (m *AccessToken) GetTokenType() isAccessToken_TokenType {
	if m != nil {
		return m.TokenType
	}
	return nil
}

func (m *AccessToken) GetRemoteToken() *HttpUri {
	if x, ok := m.GetTokenType().(*AccessToken_RemoteToken); ok {
		return x.RemoteToken
	}
	return nil
}

func (m *AccessToken) GetServiceAccountSecret() *DataSource {
	if x, ok := m.GetTokenType().(*AccessToken_ServiceAccountSecret); ok {
		return x.ServiceAccountSecret
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AccessToken) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AccessToken_RemoteToken)(nil),
		(*AccessToken_ServiceAccountSecret)(nil),
	}
}

func init() {
	proto.RegisterType((*Pattern)(nil), "google.api.envoy.http.common.Pattern")
	proto.RegisterType((*HttpUri)(nil), "google.api.envoy.http.common.HttpUri")
	proto.RegisterType((*DataSource)(nil), "google.api.envoy.http.common.DataSource")
	proto.RegisterType((*AccessToken)(nil), "google.api.envoy.http.common.AccessToken")
}

func init() { proto.RegisterFile("api/envoy/http/common/base.proto", fileDescriptor_714cdd8deafbad4d) }

var fileDescriptor_714cdd8deafbad4d = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0x33, 0x09, 0x25, 0xcd, 0x73, 0xd8, 0x8c, 0x10, 0x84, 0x82, 0x20, 0x04, 0x21, 0xb2,
	0x1a, 0xa3, 0x70, 0x00, 0xd4, 0xa8, 0x0b, 0x0b, 0xa9, 0x12, 0x72, 0xca, 0xda, 0x4c, 0x26, 0x2f,
	0xe9, 0x08, 0x7b, 0xc6, 0x1a, 0xbf, 0x89, 0x54, 0x71, 0x05, 0x4e, 0xc2, 0x09, 0x10, 0xab, 0x6e,
	0x39, 0x4a, 0x6f, 0x81, 0x3c, 0xe3, 0x40, 0xa5, 0x4a, 0xdd, 0xd9, 0xef, 0x7d, 0xff, 0xef, 0xff,
	0xfd, 0x86, 0xa9, 0xac, 0x75, 0x8a, 0x66, 0x6f, 0xaf, 0xd2, 0x4b, 0xa2, 0x3a, 0x55, 0xb6, 0xaa,
	0xac, 0x49, 0xd7, 0xb2, 0x41, 0x51, 0x3b, 0x4b, 0x96, 0xbf, 0xd8, 0x59, 0xbb, 0x2b, 0x51, 0xc8,
	0x5a, 0x8b, 0x00, 0x8a, 0x16, 0x14, 0x11, 0x3c, 0x79, 0x19, 0xb7, 0x69, 0x60, 0xd7, 0x7e, 0x9b,
	0x6e, 0xbc, 0x93, 0xa4, 0xad, 0x89, 0xea, 0x93, 0xa7, 0x7b, 0x59, 0xea, 0x8d, 0x24, 0x4c, 0x0f,
	0x0f, 0x71, 0x31, 0x3b, 0x87, 0xe1, 0x67, 0x49, 0x84, 0xce, 0xf0, 0xd7, 0x30, 0xf6, 0x4e, 0x17,
	0x84, 0x55, 0x5d, 0x4a, 0xc2, 0x09, 0x9b, 0xb2, 0xf9, 0x28, 0x4f, 0xbc, 0xd3, 0x17, 0xdd, 0x88,
	0xbf, 0x82, 0xa4, 0xfd, 0x6a, 0x51, 0x21, 0x5d, 0xda, 0xcd, 0xa4, 0x1f, 0x08, 0x68, 0x47, 0xe7,
	0x61, 0x32, 0xfb, 0xc1, 0x60, 0x98, 0x11, 0xd5, 0x5f, 0x9c, 0xe6, 0xcf, 0x61, 0xe0, 0x9d, 0x8e,
	0x36, 0xcb, 0xd1, 0xef, 0x9b, 0xeb, 0xc1, 0x03, 0xd7, 0x9f, 0xb2, 0xbc, 0x9d, 0xf2, 0x37, 0x30,
	0x54, 0xa5, 0x6f, 0x08, 0x5d, 0x74, 0xb9, 0x0d, 0x1c, 0x36, 0xfc, 0x23, 0x0c, 0x49, 0x57, 0x68,
	0x3d, 0x4d, 0x06, 0x53, 0x36, 0x4f, 0x16, 0xcf, 0x44, 0xd7, 0xc2, 0xe1, 0x4e, 0x71, 0xd6, 0xdd,
	0xb9, 0x84, 0x56, 0x7f, 0xf4, 0x93, 0xf5, 0x8f, 0x59, 0x7e, 0x50, 0xcd, 0xbe, 0x03, 0x9c, 0x49,
	0x92, 0x2b, 0xeb, 0x9d, 0x42, 0xfe, 0x0e, 0x8e, 0xb7, 0xba, 0x44, 0x23, 0x2b, 0xbc, 0x93, 0x2a,
	0xeb, 0xe5, 0xff, 0x96, 0xfc, 0x3d, 0x3c, 0xd2, 0xa6, 0xd4, 0x06, 0x8b, 0x86, 0x9c, 0x36, 0xbb,
	0x3b, 0x11, 0xb3, 0x5e, 0x3e, 0x8e, 0xc4, 0x2a, 0x00, 0x4b, 0x0e, 0xa3, 0xa6, 0x46, 0xa5, 0xb7,
	0x1a, 0x1d, 0x3f, 0xfa, 0x75, 0x73, 0x3d, 0x60, 0xb3, 0x3f, 0x0c, 0x92, 0x53, 0xa5, 0xb0, 0x69,
	0x2e, 0xec, 0x37, 0x34, 0xfc, 0x13, 0x8c, 0x1d, 0x56, 0x96, 0xb0, 0xa0, 0xf6, 0x3d, 0x44, 0x48,
	0x16, 0x6f, 0xc5, 0x7d, 0x3f, 0x56, 0x74, 0x65, 0x66, 0xbd, 0x3c, 0x89, 0xe2, 0xe8, 0xf5, 0x15,
	0x9e, 0x34, 0xe8, 0xf6, 0x5a, 0x61, 0x21, 0x95, 0xb2, 0xde, 0x50, 0xd1, 0xa0, 0x72, 0x48, 0x21,
	0x6a, 0xb2, 0x98, 0xdf, 0xef, 0xfa, 0xbf, 0x94, 0xac, 0x97, 0x3f, 0xee, 0x9c, 0x4e, 0xa3, 0xd1,
	0x2a, 0xf8, 0x2c, 0xc7, 0x00, 0x21, 0x66, 0x41, 0x57, 0x35, 0xae, 0x1f, 0x86, 0xc2, 0x3f, 0xfc,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0x40, 0x05, 0x4a, 0x8b, 0xa8, 0x02, 0x00, 0x00,
}
