// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/envoy/http/common/pattern.proto

package common

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pattern struct {
	UriTemplate          string   `protobuf:"bytes,1,opt,name=uri_template,json=uriTemplate,proto3" json:"uri_template,omitempty"`
	HttpMethod           string   `protobuf:"bytes,2,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pattern) Reset()         { *m = Pattern{} }
func (m *Pattern) String() string { return proto.CompactTextString(m) }
func (*Pattern) ProtoMessage()    {}
func (*Pattern) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f667392aafbd03b, []int{0}
}

func (m *Pattern) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pattern.Unmarshal(m, b)
}
func (m *Pattern) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pattern.Marshal(b, m, deterministic)
}
func (m *Pattern) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pattern.Merge(m, src)
}
func (m *Pattern) XXX_Size() int {
	return xxx_messageInfo_Pattern.Size(m)
}
func (m *Pattern) XXX_DiscardUnknown() {
	xxx_messageInfo_Pattern.DiscardUnknown(m)
}

var xxx_messageInfo_Pattern proto.InternalMessageInfo

func (m *Pattern) GetUriTemplate() string {
	if m != nil {
		return m.UriTemplate
	}
	return ""
}

func (m *Pattern) GetHttpMethod() string {
	if m != nil {
		return m.HttpMethod
	}
	return ""
}

func init() {
	proto.RegisterType((*Pattern)(nil), "google.api.envoy.http.common.Pattern")
}

func init() {
	proto.RegisterFile("api/envoy/http/common/pattern.proto", fileDescriptor_1f667392aafbd03b)
}

var fileDescriptor_1f667392aafbd03b = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4e, 0x2c, 0xc8, 0xd4,
	0x4f, 0xcd, 0x2b, 0xcb, 0xaf, 0xd4, 0xcf, 0x28, 0x29, 0x29, 0xd0, 0x4f, 0xce, 0xcf, 0xcd, 0xcd,
	0xcf, 0xd3, 0x2f, 0x48, 0x2c, 0x29, 0x49, 0x2d, 0xca, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4b, 0x2c, 0xc8, 0xd4, 0x03, 0xab, 0xd5, 0x03,
	0xa9, 0xd5, 0x83, 0xa8, 0x55, 0xf2, 0xe5, 0x62, 0x0f, 0x80, 0x28, 0x17, 0x52, 0xe4, 0xe2, 0x29,
	0x2d, 0xca, 0x8c, 0x2f, 0x49, 0xcd, 0x2d, 0xc8, 0x49, 0x2c, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0xe2, 0x2e, 0x2d, 0xca, 0x0c, 0x81, 0x0a, 0x09, 0xc9, 0x73, 0x71, 0x83, 0x34, 0xc7,
	0xe7, 0xa6, 0x96, 0x64, 0xe4, 0xa7, 0x48, 0x30, 0x81, 0x55, 0x70, 0x81, 0x84, 0x7c, 0xc1, 0x22,
	0x49, 0x6c, 0x60, 0x3b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x54, 0x19, 0x64, 0x09, 0x9a,
	0x00, 0x00, 0x00,
}
